#pragma once

enum eAudioFlag
{
	AudioFlagActivateSwitchWheelAudio,
	AudioFlagAllowCutsceneOverScreenFade,
	AudioFlagAllowForceRadioAfterRetune,
	AudioFlagAllowPainAndAmbientSpeechToPlayDuringCutscene,
	AudioFlagAllowPlayerAIOnMission,
	AudioFlagAllowPoliceScannerWhenPlayerHasNoControl,
	AudioFlagAllowRadioDuringSwitch,
	AudioFlagAllowRadioOverScreenFade,
	AudioFlagAllowScoreAndRadio,
	AudioFlagAllowScriptedSpeechInSlowMo,
	AudioFlagAvoidMissionCompleteDelay,
	AudioFlagDisableAbortConversationForDeathAndInjury,
	AudioFlagDisableAbortConversationForRagdoll,
	AudioFlagDisableBarks,
	AudioFlagDisableFlightMusic,
	AudioFlagDisableReplayScriptStreamRecording,
	AudioFlagEnableHeadsetBeep,
	AudioFlagForceConversationInterrupt,
	AudioFlagForceSeamlessRadioSwitch,
	AudioFlagForceSniperAudio,
	AudioFlagFrontendRadioDisabled,
	AudioFlagHoldMissionCompleteWhenPrepared,
	AudioFlagIsDirectorModeActive,
	AudioFlagIsPlayerOnMissionForSpeech,
	AudioFlagListenerReverbDisabled,
	AudioFlagLoadMPData,
	AudioFlagMobileRadioInGame,
	AudioFlagOnlyAllowScriptTriggerPoliceScanner,
	AudioFlagPlayMenuMusic,
	AudioFlagPoliceScannerDisabled,
	AudioFlagScriptedConvListenerMaySpeak,
	AudioFlagSpeechDucksScore,
	AudioFlagSuppressPlayerScubaBreathing,
	AudioFlagWantedMusicDisabled,
	AudioFlagWantedMusicOnMission
};

enum eBlipColor
{
	ColorWhite = 0,
	ColorRed = 1,
	ColorGreen = 2,
	ColorBlue = 3,
	ColorPlayer = 4,
	ColorYellow = 5,
	ColorPurple = 7,
	ColorVehicle = 38,
	ColorMichael = 42,
	ColorFranklin = 43,
	ColorTrevor = 44,
	ColorMissionRed = 49,
	ColorMissionVehicle = 54,
	ColorYellowMission = 66,
	ColorYellowMission2 = 60,
	ColorWaypoint = 83,
};

enum eBlipSprite
{
	SpriteStandard = 1,
	SpriteBig = 2,
	SpritePoliceOfficer = 3,
	SpritePoliceArea = 4,
	SpriteSquare = 5,
	SpritePlayer = 6,
	SpriteNorth = 7,
	SpriteWaypoint = 8,
	SpriteBigCircle = 9,
	SpriteBigCircleOutline = 10,
	SpriteArrowUpOutlined = 11,
	SpriteArrowDownOutlined = 12,
	SpriteArrowUp = 13,
	SpriteArrowDown = 14,
	SpritePoliceHelicopterAnimated = 15,
	SpriteJet = 16,
	SpriteNumber1 = 17,
	SpriteNumber2 = 18,
	SpriteNumber3 = 19,
	SpriteNumber4 = 20,
	SpriteNumber5 = 21,
	SpriteNumber6 = 22,
	SpriteNumber7 = 23,
	SpriteNumber8 = 24,
	SpriteNumber9 = 25,
	SpriteNumber10 = 26,
	SpriteGTAOCrew = 27,
	SpriteGTAOFriendly = 28,
	SpriteLift = 36,
	SpriteRaceFinish = 38,
	SpriteSafehouse = 40,
	SpritePoliceOfficer2 = 41,
	SpritePoliceCarDot = 42,
	SpritePoliceHelicopter = 43,
	SpriteChatBubble = 47,
	SpriteGarage2 = 50,
	SpriteDrugs = 51,
	SpriteStore = 52,
	SpritePoliceCar = 56,
	SpritePolicePlayer = 58,
	SpritePoliceStation = 60,
	SpriteHospital = 61,
	SpriteHelicopter = 64,
	SpriteStrangersAndFreaks = 65,
	SpriteArmoredTruck = 66,
	SpriteTowTruck = 68,
	SpriteBarber = 71,
	SpriteLosSantosCustoms = 72,
	SpriteClothes = 73,
	SpriteTattooParlor = 75,
	SpriteSimeon = 76,
	SpriteLester = 77,
	SpriteMichael = 78,
	SpriteTrevor = 79,
	SpriteRampage = 84,
	SpriteVinewoodTours = 85,
	SpriteLamar = 86,
	SpriteFranklin = 88,
	SpriteChinese = 89,
	SpriteAirport = 90,
	SpriteBar = 93,
	SpriteBaseJump = 94,
	SpriteCarWash = 100,
	SpriteComedyClub = 102,
	SpriteDart = 103,
	SpriteFIB = 106,
	SpriteDollarSign = 108,
	SpriteGolf = 109,
	SpriteAmmuNation = 110,
	SpriteExile = 112,
	SpriteShootingRange = 119,
	SpriteSolomon = 120,
	SpriteStripClub = 121,
	SpriteTennis = 122,
	SpriteTriathlon = 126,
	SpriteOffRoadRaceFinish = 127,
	SpriteKey = 134,
	SpriteMovieTheater = 135,
	SpriteMusic = 136,
	SpriteMarijuana = 140,
	SpriteHunting = 141,
	SpriteArmsTraffickingGround = 147,
	SpriteNigel = 149,
	SpriteAssaultRifle = 150,
	SpriteBat = 151,
	SpriteGrenade = 152,
	SpriteHealth = 153,
	SpriteKnife = 154,
	SpriteMolotov = 155,
	SpritePistol = 156,
	SpriteRPG = 157,
	SpriteShotgun = 158,
	SpriteSMG = 159,
	SpriteSniper = 160,
	SpriteSonicWave = 161,
	SpritePointOfInterest = 162,
	SpriteGTAOPassive = 163,
	SpriteGTAOUsingMenu = 164,
	SpriteLink = 171,
	SpriteMinigun = 173,
	SpriteGrenadeLauncher = 174,
	SpriteArmor = 175,
	SpriteCastle = 176,
	SpriteCamera = 184,
	SpriteHandcuffs = 188,
	SpriteYoga = 197,
	SpriteCab = 198,
	SpriteNumber11 = 199,
	SpriteNumber12 = 200,
	SpriteNumber13 = 201,
	SpriteNumber14 = 202,
	SpriteNumber15 = 203,
	SpriteNumber16 = 204,
	SpriteShrink = 205,
	SpriteEpsilon = 206,
	SpritePersonalVehicleCar = 225,
	SpritePersonalVehicleBike = 226,
	SpriteCustody = 237,
	SpriteArmsTraffickingAir = 251,
	SpriteFairground = 266,
	SpritePropertyManagement = 267,
	SpriteAltruist = 269,
	SpriteEnemy = 270,
	SpriteChop = 273,
	SpriteDead = 274,
	SpriteHooker = 279,
	SpriteFriend = 280,
	SpriteBountyHit = 303,
	SpriteGTAOMission = 304,
	SpriteGTAOSurvival = 305,
	SpriteCrateDrop = 306,
	SpritePlaneDrop = 307,
	SpriteSub = 308,
	SpriteRace = 309,
	SpriteDeathmatch = 310,
	SpriteArmWrestling = 311,
	SpriteAmmuNationShootingRange = 313,
	SpriteRaceAir = 314,
	SpriteRaceCar = 315,
	SpriteRaceSea = 316,
	SpriteGarbageTruck = 318,
	SpriteMotorCycle = 348,
	SpriteSafehouseForSale = 350,
	SpritePackage = 351,
	SpriteMartinMadrazo = 352,
	SpriteEnemyHelicopter = 353,
	SpriteBoost = 354,
	SpriteDevin = 355,
	SpriteMarina = 356,
	SpriteGarage = 357,
	SpriteGolfFlag = 358,
	SpriteHangar = 359,
	SpriteHelipad = 360,
	SpriteJerryCan = 361,
	SpriteMasks = 362,
	SpriteHeistSetup = 363,
	SpriteIncapacitated = 364,
	SpritePickupSpawn = 365,
	SpriteBoilerSuit = 366,
	SpriteCompleted = 367,
	SpriteRockets = 368,
	SpriteGarageForSale = 369,
	SpriteHelipadForSale = 370,
	SpriteMarinaForSale = 371,
	SpriteHangarForSale = 372,
	SpriteBusiness = 374,
	SpriteBusinessForSale = 375,
	SpriteRaceBike = 376,
	SpriteParachute = 377,
	SpriteTeamDeathmatch = 378,
	SpriteRaceFoot = 379,
	SpriteVehicleDeathmatch = 380,
	SpriteBarry = 381,
	SpriteDom = 382,
	SpriteMaryAnn = 383,
	SpriteCletus = 384,
	SpriteJosh = 385,
	SpriteMinute = 386,
	SpriteOmega = 387,
	SpriteTonya = 388,
	SpritePaparazzo = 389,
	SpriteCrosshair = 390,
	SpriteCreator = 398,
	SpriteCreatorDirection = 399,
	SpriteAbigail = 400,
	SpriteBlimp = 401,
	SpriteRepair = 402,
	SpriteTestosterone = 403,
	SpriteDinghy = 404,
	SpriteFanatic = 405,
	SpriteInformation = 407,
	SpriteCaptureBriefcase = 408,
	SpriteLastTeamStanding = 409,
	SpriteBoat = 410,
	SpriteCaptureHouse = 411,
	SpriteJerryCan2 = 415,
	SpriteRP = 416,
	SpriteGTAOPlayerSafehouse = 417,
	SpriteGTAOPlayerSafehouseDead = 418,
	SpriteCaptureAmericanFlag = 419,
	SpriteCaptureFlag = 420,
	SpriteTank = 421,
	SpriteHelicopterAnimated = 422,
	SpritePlane = 423,
	SpriteJet2 = 424,
	SpritePlayerNoColor = 425,
	SpriteGunCar = 426,
	SpriteSpeedboat = 427,
	SpriteHeist = 428,
	SpriteStopwatch = 430,
	SpriteDollarSignCircled = 431,
	SpriteCrosshair2 = 432,
	SpriteDollarSignSquared = 434,
};

enum eCameraShake
{
	CameraShakeHand = 0,
	CameraShakeSmallExplosion,
	CameraShakeMediumExplosion,
	CameraShakeLargeExplosion,
	CameraShakeJolt,
	CameraShakeVibrate,
	CameraShakeRoadVibration,
	CameraShakeDrunk,
	CameraShakeSkyDiving,
	CameraShakeFamilyDrugTrip,
	CameraShakeDeathFail
};

enum eControl
{
	ControlNextCamera = 0,
	ControlLookLeftRight = 1,
	ControlLookUpDown = 2,
	ControlLookUpOnly = 3,
	ControlLookDownOnly = 4,
	ControlLookLeftOnly = 5,
	ControlLookRightOnly = 6,
	ControlCinematicSlowMo = 7,
	ControlFlyUpDown = 8,
	ControlFlyLeftRight = 9,
	ControlScriptedFlyZUp = 10,
	ControlScriptedFlyZDown = 11,
	ControlWeaponWheelUpDown = 12,
	ControlWeaponWheelLeftRight = 13,
	ControlWeaponWheelNext = 14,
	ControlWeaponWheelPrev = 15,
	ControlSelectNextWeapon = 16,
	ControlSelectPrevWeapon = 17,
	ControlSkipCutscene = 18,
	ControlCharacterWheel = 19,
	ControlMultiplayerInfo = 20,
	ControlSprint = 21,
	ControlJump = 22,
	ControlEnter = 23,
	ControlAttack = 24,
	ControlAim = 25,
	ControlLookBehind = 26,
	ControlPhone = 27,
	ControlSpecialAbility = 28,
	ControlSpecialAbilitySecondary = 29,
	ControlMoveLeftRight = 30,
	ControlMoveUpDown = 31,
	ControlMoveUpOnly = 32,
	ControlMoveDownOnly = 33,
	ControlMoveLeftOnly = 34,
	ControlMoveRightOnly = 35,
	ControlDuck = 36,
	ControlSelectWeapon = 37,
	ControlPickup = 38,
	ControlSniperZoom = 39,
	ControlSniperZoomInOnly = 40,
	ControlSniperZoomOutOnly = 41,
	ControlSniperZoomInSecondary = 42,
	ControlSniperZoomOutSecondary = 43,
	ControlCover = 44,
	ControlReload = 45,
	ControlTalk = 46,
	ControlDetonate = 47,
	ControlHUDSpecial = 48,
	ControlArrest = 49,
	ControlAccurateAim = 50,
	ControlContext = 51,
	ControlContextSecondary = 52,
	ControlWeaponSpecial = 53,
	ControlWeaponSpecial2 = 54,
	ControlDive = 55,
	ControlDropWeapon = 56,
	ControlDropAmmo = 57,
	ControlThrowGrenade = 58,
	ControlVehicleMoveLeftRight = 59,
	ControlVehicleMoveUpDown = 60,
	ControlVehicleMoveUpOnly = 61,
	ControlVehicleMoveDownOnly = 62,
	ControlVehicleMoveLeftOnly = 63,
	ControlVehicleMoveRightOnly = 64,
	ControlVehicleSpecial = 65,
	ControlVehicleGunLeftRight = 66,
	ControlVehicleGunUpDown = 67,
	ControlVehicleAim = 68,
	ControlVehicleAttack = 69,
	ControlVehicleAttack2 = 70,
	ControlVehicleAccelerate = 71,
	ControlVehicleBrake = 72,
	ControlVehicleDuck = 73,
	ControlVehicleHeadlight = 74,
	ControlVehicleExit = 75,
	ControlVehicleHandbrake = 76,
	ControlVehicleHotwireLeft = 77,
	ControlVehicleHotwireRight = 78,
	ControlVehicleLookBehind = 79,
	ControlVehicleCinCam = 80,
	ControlVehicleNextRadio = 81,
	ControlVehiclePrevRadio = 82,
	ControlVehicleNextRadioTrack = 83,
	ControlVehiclePrevRadioTrack = 84,
	ControlVehicleRadioWheel = 85,
	ControlVehicleHorn = 86,
	ControlVehicleFlyThrottleUp = 87,
	ControlVehicleFlyThrottleDown = 88,
	ControlVehicleFlyYawLeft = 89,
	ControlVehicleFlyYawRight = 90,
	ControlVehiclePassengerAim = 91,
	ControlVehiclePassengerAttack = 92,
	ControlVehicleSpecialAbilityFranklin = 93,
	ControlVehicleStuntUpDown = 94,
	ControlVehicleCinematicUpDown = 95,
	ControlVehicleCinematicUpOnly = 96,
	ControlVehicleCinematicDownOnly = 97,
	ControlVehicleCinematicLeftRight = 98,
	ControlVehicleSelectNextWeapon = 99,
	ControlVehicleSelectPrevWeapon = 100,
	ControlVehicleRoof = 101,
	ControlVehicleJump = 102,
	ControlVehicleGrapplingHook = 103,
	ControlVehicleShuffle = 104,
	ControlVehicleDropProjectile = 105,
	ControlVehicleMouseControlOverride = 106,
	ControlVehicleFlyRollLeftRight = 107,
	ControlVehicleFlyRollLeftOnly = 108,
	ControlVehicleFlyRollRightOnly = 109,
	ControlVehicleFlyPitchUpDown = 110,
	ControlVehicleFlyPitchUpOnly = 111,
	ControlVehicleFlyPitchDownOnly = 112,
	ControlVehicleFlyUnderCarriage = 113,
	ControlVehicleFlyAttack = 114,
	ControlVehicleFlySelectNextWeapon = 115,
	ControlVehicleFlySelectPrevWeapon = 116,
	ControlVehicleFlySelectTargetLeft = 117,
	ControlVehicleFlySelectTargetRight = 118,
	ControlVehicleFlyVerticalFlightMode = 119,
	ControlVehicleFlyDuck = 120,
	ControlVehicleFlyAttackCamera = 121,
	ControlVehicleFlyMouseControlOverride = 122,
	ControlVehicleSubTurnLeftRight = 123,
	ControlVehicleSubTurnLeftOnly = 124,
	ControlVehicleSubTurnRightOnly = 125,
	ControlVehicleSubPitchUpDown = 126,
	ControlVehicleSubPitchUpOnly = 127,
	ControlVehicleSubPitchDownOnly = 128,
	ControlVehicleSubThrottleUp = 129,
	ControlVehicleSubThrottleDown = 130,
	ControlVehicleSubAscend = 131,
	ControlVehicleSubDescend = 132,
	ControlVehicleSubTurnHardLeft = 133,
	ControlVehicleSubTurnHardRight = 134,
	ControlVehicleSubMouseControlOverride = 135,
	ControlVehiclePushbikePedal = 136,
	ControlVehiclePushbikeSprint = 137,
	ControlVehiclePushbikeFrontBrake = 138,
	ControlVehiclePushbikeRearBrake = 139,
	ControlMeleeAttackLight = 140,
	ControlMeleeAttackHeavy = 141,
	ControlMeleeAttackAlternate = 142,
	ControlMeleeBlock = 143,
	ControlParachuteDeploy = 144,
	ControlParachuteDetach = 145,
	ControlParachuteTurnLeftRight = 146,
	ControlParachuteTurnLeftOnly = 147,
	ControlParachuteTurnRightOnly = 148,
	ControlParachutePitchUpDown = 149,
	ControlParachutePitchUpOnly = 150,
	ControlParachutePitchDownOnly = 151,
	ControlParachuteBrakeLeft = 152,
	ControlParachuteBrakeRight = 153,
	ControlParachuteSmoke = 154,
	ControlParachutePrecisionLanding = 155,
	ControlMap = 156,
	ControlSelectWeaponUnarmed = 157,
	ControlSelectWeaponMelee = 158,
	ControlSelectWeaponHandgun = 159,
	ControlSelectWeaponShotgun = 160,
	ControlSelectWeaponSmg = 161,
	ControlSelectWeaponAutoRifle = 162,
	ControlSelectWeaponSniper = 163,
	ControlSelectWeaponHeavy = 164,
	ControlSelectWeaponSpecial = 165,
	ControlSelectCharacterMichael = 166,
	ControlSelectCharacterFranklin = 167,
	ControlSelectCharacterTrevor = 168,
	ControlSelectCharacterMultiplayer = 169,
	ControlSaveReplayClip = 170,
	ControlSpecialAbilityPC = 171,
	ControlPhoneUp = 172,
	ControlPhoneDown = 173,
	ControlPhoneLeft = 174,
	ControlPhoneRight = 175,
	ControlPhoneSelect = 176,
	ControlPhoneCancel = 177,
	ControlPhoneOption = 178,
	ControlPhoneExtraOption = 179,
	ControlPhoneScrollForward = 180,
	ControlPhoneScrollBackward = 181,
	ControlPhoneCameraFocusLock = 182,
	ControlPhoneCameraGrid = 183,
	ControlPhoneCameraSelfie = 184,
	ControlPhoneCameraDOF = 185,
	ControlPhoneCameraExpression = 186,
	ControlFrontendDown = 187,
	ControlFrontendUp = 188,
	ControlFrontendLeft = 189,
	ControlFrontendRight = 190,
	ControlFrontendRdown = 191,
	ControlFrontendRup = 192,
	ControlFrontendRleft = 193,
	ControlFrontendRright = 194,
	ControlFrontendAxisX = 195,
	ControlFrontendAxisY = 196,
	ControlFrontendRightAxisX = 197,
	ControlFrontendRightAxisY = 198,
	ControlFrontendPause = 199,
	ControlFrontendPauseAlternate = 200,
	ControlFrontendAccept = 201,
	ControlFrontendCancel = 202,
	ControlFrontendX = 203,
	ControlFrontendY = 204,
	ControlFrontendLb = 205,
	ControlFrontendRb = 206,
	ControlFrontendLt = 207,
	ControlFrontendRt = 208,
	ControlFrontendLs = 209,
	ControlFrontendRs = 210,
	ControlFrontendLeaderboard = 211,
	ControlFrontendSocialClub = 212,
	ControlFrontendSocialClubSecondary = 213,
	ControlFrontendDelete = 214,
	ControlFrontendEndscreenAccept = 215,
	ControlFrontendEndscreenExpand = 216,
	ControlFrontendSelect = 217,
	ControlScriptLeftAxisX = 218,
	ControlScriptLeftAxisY = 219,
	ControlScriptRightAxisX = 220,
	ControlScriptRightAxisY = 221,
	ControlScriptRUp = 222,
	ControlScriptRDown = 223,
	ControlScriptRLeft = 224,
	ControlScriptRRight = 225,
	ControlScriptLB = 226,
	ControlScriptRB = 227,
	ControlScriptLT = 228,
	ControlScriptRT = 229,
	ControlScriptLS = 230,
	ControlScriptRS = 231,
	ControlScriptPadUp = 232,
	ControlScriptPadDown = 233,
	ControlScriptPadLeft = 234,
	ControlScriptPadRight = 235,
	ControlScriptSelect = 236,
	ControlCursorAccept = 237,
	ControlCursorCancel = 238,
	ControlCursorX = 239,
	ControlCursorY = 240,
	ControlCursorScrollUp = 241,
	ControlCursorScrollDown = 242,
	ControlEnterCheatCode = 243,
	ControlInteractionMenu = 244,
	ControlMpTextChatAll = 245,
	ControlMpTextChatTeam = 246,
	ControlMpTextChatFriends = 247,
	ControlMpTextChatCrew = 248,
	ControlPushToTalk = 249,
	ControlCreatorLS = 250,
	ControlCreatorRS = 251,
	ControlCreatorLT = 252,
	ControlCreatorRT = 253,
	ControlCreatorMenuToggle = 254,
	ControlCreatorAccept = 255,
	ControlCreatorDelete = 256,
	ControlAttack2 = 257,
	ControlRappelJump = 258,
	ControlRappelLongJump = 259,
	ControlRappelSmashWindow = 260,
	ControlPrevWeapon = 261,
	ControlNextWeapon = 262,
	ControlMeleeAttack1 = 263,
	ControlMeleeAttack2 = 264,
	ControlWhistle = 265,
	ControlMoveLeft = 266,
	ControlMoveRight = 267,
	ControlMoveUp = 268,
	ControlMoveDown = 269,
	ControlLookLeft = 270,
	ControlLookRight = 271,
	ControlLookUp = 272,
	ControlLookDown = 273,
	ControlSniperZoomIn = 274,
	ControlSniperZoomOut = 275,
	ControlSniperZoomInAlternate = 276,
	ControlSniperZoomOutAlternate = 277,
	ControlVehicleMoveLeft = 278,
	ControlVehicleMoveRight = 279,
	ControlVehicleMoveUp = 280,
	ControlVehicleMoveDown = 281,
	ControlVehicleGunLeft = 282,
	ControlVehicleGunRight = 283,
	ControlVehicleGunUp = 284,
	ControlVehicleGunDown = 285,
	ControlVehicleLookLeft = 286,
	ControlVehicleLookRight = 287,
	ControlReplayStartStopRecording = 288,
	ControlReplayStartStopRecordingSecondary = 289,
	ControlScaledLookLeftRight = 290,
	ControlScaledLookUpDown = 291,
	ControlScaledLookUpOnly = 292,
	ControlScaledLookDownOnly = 293,
	ControlScaledLookLeftOnly = 294,
	ControlScaledLookRightOnly = 295,
	ControlReplayMarkerDelete = 296,
	ControlReplayClipDelete = 297,
	ControlReplayPause = 298,
	ControlReplayRewind = 299,
	ControlReplayFfwd = 300,
	ControlReplayNewmarker = 301,
	ControlReplayRecord = 302,
	ControlReplayScreenshot = 303,
	ControlReplayHidehud = 304,
	ControlReplayStartpoint = 305,
	ControlReplayEndpoint = 306,
	ControlReplayAdvance = 307,
	ControlReplayBack = 308,
	ControlReplayTools = 309,
	ControlReplayRestart = 310,
	ControlReplayShowhotkey = 311,
	ControlReplayCycleMarkerLeft = 312,
	ControlReplayCycleMarkerRight = 313,
	ControlReplayFOVIncrease = 314,
	ControlReplayFOVDecrease = 315,
	ControlReplayCameraUp = 316,
	ControlReplayCameraDown = 317,
	ControlReplaySave = 318,
	ControlReplayToggletime = 319,
	ControlReplayToggletips = 320,
	ControlReplayPreview = 321,
	ControlReplayToggleTimeline = 322,
	ControlReplayTimelinePickupClip = 323,
	ControlReplayTimelineDuplicateClip = 324,
	ControlReplayTimelinePlaceClip = 325,
	ControlReplayCtrl = 326,
	ControlReplayTimelineSave = 327,
	ControlReplayPreviewAudio = 328,
	ControlVehicleDriveLook = 329,
	ControlVehicleDriveLook2 = 330,
	ControlVehicleFlyAttack2 = 331,
	ControlRadioWheelUpDown = 332,
	ControlRadioWheelLeftRight = 333,
	ControlVehicleSlowMoUpDown = 334,
	ControlVehicleSlowMoUpOnly = 335,
	ControlVehicleSlowMoDownOnly = 336,
	ControlMapPointOfInterest = 337,
};

enum eRadioStation
{
	RadioStationLosSantosRockRadio,
	RadioStationNonStopPopFM,
	RadioStationLosSantos,
	RadioStationChannelX,
	RadioStationWestCoastTalkRadio,
	RadioStationRebelRadio,
	RadioStationSoulwaxFM,
	RadioStationEastLosFM,
	RadioStationWestCoastClassics,
	RadioStationTheBlueArk,
	RadioStationWorldWideFM,
	RadioStationFlyloFM,
	RadioStationTheLowdown,
	RadioStationTheLab,
	RadioStationMirrorPark,
	RadioStationSpace,
	RadioStationVinewoodBoulevardRadio,
};

enum eWindowTitle
{
	CELL_EMAIL_BOD,
	CELL_EMAIL_BODE,
	CELL_EMAIL_BODF,
	CELL_EMAIL_SOD,
	CELL_EMAIL_SODE,
	CELL_EMAIL_SODF,
	CELL_EMASH_BOD,
	CELL_EMASH_BODE,
	CELL_EMASH_BODF,
	CELL_EMASH_SOD,
	CELL_EMASH_SODE,
	CELL_EMASH_SODF,
	FMMC_KEY_TIP10,
	FMMC_KEY_TIP12,
	FMMC_KEY_TIP12F,
	FMMC_KEY_TIP12N,
	FMMC_KEY_TIP8,
	FMMC_KEY_TIP8F,
	FMMC_KEY_TIP8FS,
	FMMC_KEY_TIP8S,
	FMMC_KEY_TIP9,
	FMMC_KEY_TIP9F,
	FMMC_KEY_TIP9N,
	PM_NAME_CHALL,
};

enum eGender
{
	GenderMale,
	GenderFemale
};

enum eDrivingStyle
{
	DrivingStyleNormal = 0xC00AB,
	DrivingStyleIgnoreLights = 0x2C0025,
	DrivingStyleSometimesOvertakeTraffic = 5,
	DrivingStyleRushed = 0x400C0025,
	DrivingStyleAvoidTraffic = 0xC0024,
	DrivingStyleAvoidTrafficExtremely = 6
};

enum eBone
{
	SKEL_ROOT = 0x0,
	SKEL_Pelvis = 0x2e28,
	SKEL_L_Thigh = 0xe39f,
	SKEL_L_Calf = 0xf9bb,
	SKEL_L_Foot = 0x3779,
	SKEL_L_Toe0 = 0x83c,
	IK_L_Foot = 0xfedd,
	PH_L_Foot = 0xe175,
	MH_L_Knee = 0xb3fe,
	SKEL_R_Thigh = 0xca72,
	SKEL_R_Calf = 0x9000,
	SKEL_R_Foot = 0xcc4d,
	SKEL_R_Toe0 = 0x512d,
	IK_R_Foot = 0x8aae,
	PH_R_Foot = 0x60e6,
	MH_R_Knee = 0x3fcf,
	RB_L_ThighRoll = 0x5c57,
	RB_R_ThighRoll = 0x192a,
	SKEL_Spine_Root = 0xe0fd,
	SKEL_Spine0 = 0x5c01,
	SKEL_Spine1 = 0x60f0,
	SKEL_Spine2 = 0x60f1,
	SKEL_Spine3 = 0x60f2,
	SKEL_L_Clavicle = 0xfcd9,
	SKEL_L_UpperArm = 0xb1c5,
	SKEL_L_Forearm = 0xeeeb,
	SKEL_L_Hand = 0x49d9,
	SKEL_L_Finger00 = 0x67f2,
	SKEL_L_Finger01 = 0xff9,
	SKEL_L_Finger02 = 0xffa,
	SKEL_L_Finger10 = 0x67f3,
	SKEL_L_Finger11 = 0x1049,
	SKEL_L_Finger12 = 0x104a,
	SKEL_L_Finger20 = 0x67f4,
	SKEL_L_Finger21 = 0x1059,
	SKEL_L_Finger22 = 0x105a,
	SKEL_L_Finger30 = 0x67f5,
	SKEL_L_Finger31 = 0x1029,
	SKEL_L_Finger32 = 0x102a,
	SKEL_L_Finger40 = 0x67f6,
	SKEL_L_Finger41 = 0x1039,
	SKEL_L_Finger42 = 0x103a,
	PH_L_Hand = 0xeb95,
	IK_L_Hand = 0x8cbd,
	RB_L_ForeArmRoll = 0xee4f,
	RB_L_ArmRoll = 0x1470,
	MH_L_Elbow = 0x58b7,
	SKEL_R_Clavicle = 0x29d2,
	SKEL_R_UpperArm = 0x9d4d,
	SKEL_R_Forearm = 0x6e5c,
	SKEL_R_Hand = 0xdead,
	SKEL_R_Finger00 = 0xe5f2,
	SKEL_R_Finger01 = 0xfa10,
	SKEL_R_Finger02 = 0xfa11,
	SKEL_R_Finger10 = 0xe5f3,
	SKEL_R_Finger11 = 0xfa60,
	SKEL_R_Finger12 = 0xfa61,
	SKEL_R_Finger20 = 0xe5f4,
	SKEL_R_Finger21 = 0xfa70,
	SKEL_R_Finger22 = 0xfa71,
	SKEL_R_Finger30 = 0xe5f5,
	SKEL_R_Finger31 = 0xfa40,
	SKEL_R_Finger32 = 0xfa41,
	SKEL_R_Finger40 = 0xe5f6,
	SKEL_R_Finger41 = 0xfa50,
	SKEL_R_Finger42 = 0xfa51,
	PH_R_Hand = 0x6f06,
	IK_R_Hand = 0x188e,
	RB_R_ForeArmRoll = 0xab22,
	RB_R_ArmRoll = 0x90ff,
	MH_R_Elbow = 0xbb0,
	SKEL_Neck_1 = 0x9995,
	SKEL_Head = 0x796e,
	IK_Head = 0x322c,
	FACIAL_facialRoot = 0xfe2c,
	FB_L_Brow_Out_000 = 0xe3db,
	FB_L_Lid_Upper_000 = 0xb2b6,
	FB_L_Eye_000 = 0x62ac,
	FB_L_CheekBone_000 = 0x542e,
	FB_L_Lip_Corner_000 = 0x74ac,
	FB_R_Lid_Upper_000 = 0xaa10,
	FB_R_Eye_000 = 0x6b52,
	FB_R_CheekBone_000 = 0x4b88,
	FB_R_Brow_Out_000 = 0x54c,
	FB_R_Lip_Corner_000 = 0x2ba6,
	FB_Brow_Centre_000 = 0x9149,
	FB_UpperLipRoot_000 = 0x4ed2,
	FB_UpperLip_000 = 0xf18f,
	FB_L_Lip_Top_000 = 0x4f37,
	FB_R_Lip_Top_000 = 0x4537,
	FB_Jaw_000 = 0xb4a0,
	FB_LowerLipRoot_000 = 0x4324,
	FB_LowerLip_000 = 0x508f,
	FB_L_Lip_Bot_000 = 0xb93b,
	FB_R_Lip_Bot_000 = 0xc33b,
	FB_Tongue_000 = 0xb987,
	RB_Neck_1 = 0x8b93,
	IK_Root = 0xdd1c
};

enum eFiringPattern : DWORD
{
	FiringPatternFullAuto = 0xC6EE6B4C,
	FiringPatternBurstFire = 0xD6FF6D61,
	FiringPatternBurstInCover = 0x026321F1,
	FiringPatternBurstFireDriveby = 0xD31265F2,
	FiringPatternFromGround = 0x2264E5D6,
	FiringPatternDelayFireByOneSec = 0x7A845691,
	FiringPatternSingleShot = 0x5D60E4E0,
	FiringPatternBurstFirePistol = 0xA018DB8A,
	FiringPatternBurstFireSMG = 0xD10DADEE,
	FiringPatternBurstFireRifle = 0x9C74B406,
	FiringPatternBurstFireMG = 0xB573C5B4,
	FiringPatternBurstFirePumpShotGun = 0x00BAC39B,
	FiringPatternBurstFireHeli = 0x914E786F,
	FiringPatternBurstFireMicro = 0x42EF03FD,
	FiringPatternBurstFireBursts = 0x42EF03FD,
	FiringPatternBurstFireTank = 0xE2CA3A71
};

enum eFont
{
	FontChaletLondon = 0,
	FontHouseScript = 1,
	FontMonospace = 2,
	FontWingDings = 3,
	FontChaletComprimeCologne = 4,
	FontPricedown = 7
};

enum eVehicleColor
{
	VehicleColorMetallicBlack = 0,
	VehicleColorMetallicGraphiteBlack = 1,
	VehicleColorMetallicBlackSteel = 2,
	VehicleColorMetallicDarkSilver = 3,
	VehicleColorMetallicSilver = 4,
	VehicleColorMetallicBlueSilver = 5,
	VehicleColorMetallicSteelGray = 6,
	VehicleColorMetallicShadowSilver = 7,
	VehicleColorMetallicStoneSilver = 8,
	VehicleColorMetallicMidnightSilver = 9,
	VehicleColorMetallicGunMetal = 10,
	VehicleColorMetallicAnthraciteGray = 11,
	VehicleColorMatteBlack = 12,
	VehicleColorMatteGray = 13,
	VehicleColorMatteLightGray = 14,
	VehicleColorUtilBlack = 15,
	VehicleColorUtilBlackPoly = 16,
	VehicleColorUtilDarksilver = 17,
	VehicleColorUtilSilver = 18,
	VehicleColorUtilGunMetal = 19,
	VehicleColorUtilShadowSilver = 20,
	VehicleColorWornBlack = 21,
	VehicleColorWornGraphite = 22,
	VehicleColorWornSilverGray = 23,
	VehicleColorWornSilver = 24,
	VehicleColorWornBlueSilver = 25,
	VehicleColorWornShadowSilver = 26,
	VehicleColorMetallicRed = 27,
	VehicleColorMetallicTorinoRed = 28,
	VehicleColorMetallicFormulaRed = 29,
	VehicleColorMetallicBlazeRed = 30,
	VehicleColorMetallicGracefulRed = 31,
	VehicleColorMetallicGarnetRed = 32,
	VehicleColorMetallicDesertRed = 33,
	VehicleColorMetallicCabernetRed = 34,
	VehicleColorMetallicCandyRed = 35,
	VehicleColorMetallicSunriseOrange = 36,
	VehicleColorMetallicClassicGold = 37,
	VehicleColorMetallicOrange = 38,
	VehicleColorMatteRed = 39,
	VehicleColorMatteDarkRed = 40,
	VehicleColorMatteOrange = 41,
	VehicleColorMatteYellow = 42,
	VehicleColorUtilRed = 43,
	VehicleColorUtilBrightRed = 44,
	VehicleColorUtilGarnetRed = 45,
	VehicleColorWornRed = 46,
	VehicleColorWornGoldenRed = 47,
	VehicleColorWornDarkRed = 48,
	VehicleColorMetallicDarkGreen = 49,
	VehicleColorMetallicRacingGreen = 50,
	VehicleColorMetallicSeaGreen = 51,
	VehicleColorMetallicOliveGreen = 52,
	VehicleColorMetallicGreen = 53,
	VehicleColorMetallicGasolineBlueGreen = 54,
	VehicleColorMatteLimeGreen = 55,
	VehicleColorUtilDarkGreen = 56,
	VehicleColorUtilGreen = 57,
	VehicleColorWornDarkGreen = 58,
	VehicleColorWornGreen = 59,
	VehicleColorWornSeaWash = 60,
	VehicleColorMetallicMidnightBlue = 61,
	VehicleColorMetallicDarkBlue = 62,
	VehicleColorMetallicSaxonyBlue = 63,
	VehicleColorMetallicBlue = 64,
	VehicleColorMetallicMarinerBlue = 65,
	VehicleColorMetallicHarborBlue = 66,
	VehicleColorMetallicDiamondBlue = 67,
	VehicleColorMetallicSurfBlue = 68,
	VehicleColorMetallicNauticalBlue = 69,
	VehicleColorMetallicBrightBlue = 70,
	VehicleColorMetallicPurpleBlue = 71,
	VehicleColorMetallicSpinnakerBlue = 72,
	VehicleColorMetallicUltraBlue = 73,
	VehicleColorUtilDarkBlue = 75,
	VehicleColorUtilMidnightBlue = 76,
	VehicleColorUtilBlue = 77,
	VehicleColorUtilSeaFoamBlue = 78,
	VehicleColorUtilLightningBlue = 79,
	VehicleColorUtilMauiBluePoly = 80,
	VehicleColorUtilBrightBlue = 81,
	VehicleColorMatteDarkBlue = 82,
	VehicleColorMatteBlue = 83,
	VehicleColorMatteMidnightBlue = 84,
	VehicleColorWornDarkBlue = 85,
	VehicleColorWornBlue = 86,
	VehicleColorWornLightBlue = 87,
	VehicleColorMetallicTaxiYellow = 88,
	VehicleColorMetallicRaceYellow = 89,
	VehicleColorMetallicBronze = 90,
	VehicleColorMetallicYellowBird = 91,
	VehicleColorMetallicLime = 92,
	VehicleColorMetallicChampagne = 93,
	VehicleColorMetallicPuebloBeige = 94,
	VehicleColorMetallicDarkIvory = 95,
	VehicleColorMetallicChocoBrown = 96,
	VehicleColorMetallicGoldenBrown = 97,
	VehicleColorMetallicLightBrown = 98,
	VehicleColorMetallicStrawBeige = 99,
	VehicleColorMetallicMossBrown = 100,
	VehicleColorMetallicBistonBrown = 101,
	VehicleColorMetallicBeechwood = 102,
	VehicleColorMetallicDarkBeechwood = 103,
	VehicleColorMetallicChocoOrange = 104,
	VehicleColorMetallicBeachSand = 105,
	VehicleColorMetallicSunBleechedSand = 106,
	VehicleColorMetallicCream = 107,
	VehicleColorUtilBrown = 108,
	VehicleColorUtilMediumBrown = 109,
	VehicleColorUtilLightBrown = 110,
	VehicleColorMetallicWhite = 111,
	VehicleColorMetallicFrostWhite = 112,
	VehicleColorWornHoneyBeige = 113,
	VehicleColorWornBrown = 114,
	VehicleColorWornDarkBrown = 115,
	VehicleColorWornStrawBeige = 116,
	VehicleColorBrushedSteel = 117,
	VehicleColorBrushedBlackSteel = 118,
	VehicleColorBrushedAluminium = 119,
	VehicleColorChrome = 120,
	VehicleColorWornOffWhite = 121,
	VehicleColorUtilOffWhite = 122,
	VehicleColorWornOrange = 123,
	VehicleColorWornLightOrange = 124,
	VehicleColorMetallicSecuricorGreen = 125,
	VehicleColorWornTaxiYellow = 126,
	VehicleColorPoliceCarBlue = 127,
	VehicleColorMatteGreen = 128,
	VehicleColorMatteBrown = 129,
	VehicleColorMatteWhite = 131,
	VehicleColorWornWhite = 132,
	VehicleColorWornOliveArmyGreen = 133,
	VehicleColorPureWhite = 134,
	VehicleColorHotPink = 135,
	VehicleColorSalmonpink = 136,
	VehicleColorMetallicVermillionPink = 137,
	VehicleColorOrange = 138,
	VehicleColorGreen = 139,
	VehicleColorBlue = 140,
	VehicleColorMettalicBlackBlue = 141,
	VehicleColorMetallicBlackPurple = 142,
	VehicleColorMetallicBlackRed = 143,
	VehicleColorHunterGreen = 144,
	VehicleColorMetallicPurple = 145,
	VehicleColorMetaillicVDarkBlue = 146,
	VehicleColorModshopBlack1 = 147,
	VehicleColorMattePurple = 148,
	VehicleColorMatteDarkPurple = 149,
	VehicleColorMetallicLavaRed = 150,
	VehicleColorMatteForestGreen = 151,
	VehicleColorMatteOliveDrab = 152,
	VehicleColorMatteDesertBrown = 153,
	VehicleColorMatteDesertTan = 154,
	VehicleColorMatteFoliageGreen = 155,
	VehicleColorDefaultAlloyColor = 156,
	VehicleColorEpsilonBlue = 157,
	VehicleColorPureGold = 158,
	VehicleColorBrushedGold = 159,
};

enum eVehicleDoor
{
	VehicleDoorFrontLeftDoor = 0,
	VehicleDoorFrontRightDoor = 1,
	VehicleDoorBackLeftDoor = 2,
	VehicleDoorBackRightDoor = 3,
	VehicleDoorHood = 4,
	VehicleDoorTrunk = 5,
	VehicleDoorTrunk2 = 6,
};

enum eVehicleLockStatus
{
	VehicleLockStatusNone = 0,
	VehicleLockStatusUnlocked = 1,
	VehicleLockStatusLocked = 2,
	VehicleLockStatusLockedForPlayer = 3,
	VehicleLockStatusStickPlayerInside = 4,
	VehicleLockStatusCanBeBrokenInto = 7,
	VehicleLockStatusCanBeBrokenIntoPersist = 8,
	VehicleLockStatusCannotBeTriedToEnter = 10
};

enum eVehicleLandingGear
{
	VehicleLandingGearDeployed = 0,
	VehicleLandingGearClosing = 1,
	VehicleLandingGearOpening = 2,
	VehicleLandingGearRetracted = 3,
};

enum eVehicleMod
{
	VehicleModSpoilers = 0,
	VehicleModFrontBumper = 1,
	VehicleModRearBumper = 2,
	VehicleModSideSkirt = 3,
	VehicleModExhaust = 4,
	VehicleModFrame = 5,
	VehicleModGrille = 6,
	VehicleModHood = 7,
	VehicleModFender = 8,
	VehicleModRightFender = 9,
	VehicleModRoof = 10,
	VehicleModEngine = 11,
	VehicleModBrakes = 12,
	VehicleModTransmission = 13,
	VehicleModHorns = 14,
	VehicleModSuspension = 15,
	VehicleModArmor = 16,
	VehicleModFrontWheels = 23,
	VehicleModBackWheels = 24 // only for motocycles
};

enum eVehicleNeonLight
{
	VehicleNeonLightLeft = 0,
	VehicleNeonLightRight = 1,
	VehicleNeonLightFront = 2,
	VehicleNeonLightBack = 3,
};

enum eVehicleRoofState
{
	VehicleRoofStateClosed,
	VehicleRoofStateOpening,
	VehicleRoofStateOpened,
	VehicleRoofStateClosing,
};

enum eVehicleSeat
{
	VehicleSeatNone = -3,
	VehicleSeatAny = -2,
	VehicleSeatDriver = -1,
	VehicleSeatPassenger = 0,
	VehicleSeatLeftFront = -1,
	VehicleSeatRightFront = 0,
	VehicleSeatLeftRear = 1,
	VehicleSeatRightRear = 2,
};

enum eVehicleToggleMod
{
	VehicleToggleModTurbo = 18,
	VehicleToggleModTireSmoke = 20,
	VehicleToggleModXenonHeadlights = 22
};

enum eVehicleWheelType
{
	VehicleWheelTypeSport = 0,
	VehicleWheelTypeMuscle = 1,
	VehicleWheelTypeLowrider = 2,
	VehicleWheelTypeSUV = 3,
	VehicleWheelTypeOffroad = 4,
	VehicleWheelTypeTuner = 5,
	VehicleWheelTypeBikeWheels = 6,
	VehicleWheelTypeHighEnd = 7
};

enum eVehicleWindow
{
	VehicleWindowFrontRight = 1,
	VehicleWindowFrontLeft = 0,
	VehicleWindowBackRight = 3,
	VehicleWindowBackLeft = 2
};

enum eVehicleWindowTint
{
	VehicleWindowTintNone = 0,
	VehicleWindowTintPureBlack = 1,
	VehicleWindowTintDarkSmoke = 2,
	VehicleWindowTintLightSmoke = 3,
	VehicleWindowTintStock = 4,
	VehicleWindowTintLimo = 5,
	VehicleWindowTintGreen = 6
};

enum eNumberPlateMounting
{
	NumberPlateMountingFrontAndRear = 0,
	NumberPlateMountingFront = 1,
	NumberPlateMountingRear = 2,
	NumberPlateMountingNone = 3,
};

enum eNumberPlateType
{
	NumberPlateTypeBlueOnWhite1 = 0,
	NumberPlateTypeYellowOnBlack = 1,
	NumberPlateTypeYellowOnBlue = 2,
	NumberPlateTypeBlueOnWhite2 = 3,
	NumberPlateTypeBlueOnWhite3 = 4,
	NumberPlateTypeNorthYankton = 5,
};

enum eVehicleClass
{
	VehicleClassCompacts = 0,
	VehicleClassSedans = 1,
	VehicleClassSUVs = 2,
	VehicleClassCoupes = 3,
	VehicleClassMuscle = 4,
	VehicleClassSportsClassics = 5,
	VehicleClassSports = 6,
	VehicleClassSuper = 7,
	VehicleClassMotorcycles = 8,
	VehicleClassOffRoad = 9,
	VehicleClassIndustrial = 10,
	VehicleClassUtility = 11,
	VehicleClassVans = 12,
	VehicleClassCycles = 13,
	VehicleClassBoats = 14,
	VehicleClassHelicopters = 15,
	VehicleClassPlanes = 16,
	VehicleClassService = 17,
	VehicleClassEmergency = 18,
	VehicleClassMilitary = 19,
	VehicleClassCommercial = 20,
	VehicleClassTrains = 21,
};

enum eExplosionType
{
	ExplosionTypeGrenade = 0,
	ExplosionTypeGrenadeL = 1,
	ExplosionTypeStickyBomb = 2,
	ExplosionTypeMolotov = 3,
	ExplosionTypeRocket = 4,
	ExplosionTypeTankShell = 5,
	ExplosionTypeHiOctane = 6,
	ExplosionTypeCar = 7,
	ExplosionTypePlane = 8,
	ExplosionTypePetrolPump = 9,
	ExplosionTypeBike = 10,
	ExplosionTypeSteam = 11,
	ExplosionTypeFlame = 12,
	ExplosionTypeWaterHydrant = 13,
	ExplosionTypeGasCanister = 14,
	ExplosionTypeBoat = 15,
	ExplosionTypeShipDestroy = 16,
	ExplosionTypeTruck = 17,
	ExplosionTypeBullet = 18,
	ExplosionTypeSmokeGL = 19,
	ExplosionTypeSmokeG = 20,
	ExplosionTypeBZGas = 21,
	ExplosionTypeFlare = 22,
	ExplosionTypeGasCanister2 = 23,
	ExplosionTypeExtinguisher = 24,
	ExplosionTypeProgramAR = 25,
	ExplosionTypeTrain = 26,
	ExplosionTypeBarrel = 27,
	ExplosionTypePropane = 28,
	ExplosionTypeBlimp = 29,
	ExplosionTypeFlameExplode = 30,
	ExplosionTypeTanker = 31,
	ExplosionTypePlaneRocket = 32,
	ExplosionTypeVehicleBullet = 33,
	ExplosionTypeGasTank = 34,
	ExplosionTypeFireWork = 35,
	ExplosionTypeSnowBall = 36,
	ExplosionTypeProxMine = 37,
	ExplosionTypeValkyrie = 38
};

enum eIntersectFlags
{
	IntersectFlagsEverything = -1,
	IntersectFlagsMap = 1,
	IntersectFlagsMissionEntities = 2,
	IntersectFlagsPeds1 = 12, // 4 and 8 both seem to be peds
	IntersectFlagsObjects = 16,
	IntersectFlagsUnk1 = 32,
	IntersectFlagsUnk2 = 64,
	IntersectFlagsUnk3 = 128,
	IntersectFlagsVegetation = 256,
	IntersectFlagsUnk4 = 512
};

enum eMarkerType
{
	MarkerTypeUpsideDownCone = 0,
	MarkerTypeVerticalCylinder = 1,
	MarkerTypeThickChevronUp = 2,
	MarkerTypeThinChevronUp = 3,
	MarkerTypeCheckeredFlagRect = 4,
	MarkerTypeCheckeredFlagCircle = 5,
	MarkerTypeVerticleCircle = 6,
	MarkerTypePlaneModel = 7,
	MarkerTypeLostMCDark = 8,
	MarkerTypeLostMCLight = 9,
	MarkerTypeNumber0 = 10,
	MarkerTypeNumber1 = 11,
	MarkerTypeNumber2 = 12,
	MarkerTypeNumber3 = 13,
	MarkerTypeNumber4 = 14,
	MarkerTypeNumber5 = 15,
	MarkerTypeNumber6 = 16,
	MarkerTypeNumber7 = 17,
	MarkerTypeNumber8 = 18,
	MarkerTypeNumber9 = 19,
	MarkerTypeChevronUpx1 = 20,
	MarkerTypeChevronUpx2 = 21,
	MarkerTypeChevronUpx3 = 22,
	MarkerTypeHorizontalCircleFat = 23,
	MarkerTypeReplayIcon = 24,
	MarkerTypeHorizontalCircleSkinny = 25,
	MarkerTypeHorizontalCircleSkinny_Arrow = 26,
	MarkerTypeHorizontalSplitArrowCircle = 27,
	MarkerTypeDebugSphere = 28
};

enum eRelationship
{
	RelationshipHate = 5,
	RelationshipDislike = 4,
	RelationshipNeutral = 3,
	RelationshipLike = 2,
	RelationshipRespect = 1,
	RelationshipCompanion = 0,
	RelationshipPedestrians = 255 // or neutral
};

enum eRopeType
{
	RopeTypeNormal = 4,
};

enum eWeapon : DWORD
{
	WeaponKnife = 0x99B507EA,
	WeaponNightstick = 0x678B81B1,
	WeaponHammer = 0x4E875F73,
	WeaponBat = 0x958A4A8F,
	WeaponGolfClub = 0x440E4788,
	WeaponCrowbar = 0x84BD7BFD,
	WeaponPistol = 0x1B06D571,
	WeaponCombatPistol = 0x5EF9FEC4,
	WeaponAPPistol = 0x22D8FE39,
	WeaponPistol50 = 0x99AEEB3B,
	WeaponMicroSMG = 0x13532244,
	WeaponSMG = 0x2BE6766B,
	WeaponAssaultSMG = 0xEFE7E2DF,
	WeaponCombatPDW = 0x0A3D4D34,
	WeaponAssaultRifle = 0xBFEFFF6D,
	WeaponCarbineRifle = 0x83BF0278,
	WeaponAdvancedRifle = 0xAF113F99,
	WeaponMG = 0x9D07F764,
	WeaponCombatMG = 0x7FD62962,
	WeaponPumpShotgun = 0x1D073A89,
	WeaponSawnOffShotgun = 0x7846A318,
	WeaponAssaultShotgun = 0xE284C527,
	WeaponBullpupShotgun = 0x9D61E50F,
	WeaponStunGun = 0x3656C8C1,
	WeaponSniperRifle = 0x5FC3C11,
	WeaponHeavySniper = 0xC472FE2,
	WeaponGrenadeLauncher = 0xA284510B,
	WeaponGrenadeLauncherSmoke = 0x4DD2DC56,
	WeaponRPG = 0xB1CA77B1,
	WeaponMinigun = 0x42BF8A85,
	WeaponGrenade = 0x93E220BD,
	WeaponStickyBomb = 0x2C3731D9,
	WeaponSmokeGrenade = 0xFDBC8A50,
	WeaponBZGas = 0xA0973D5E,
	WeaponMolotov = 0x24B17070,
	WeaponFireExtinguisher = 0x60EC506,
	WeaponPetrolCan = 0x34A67B97,
	WeaponSNSPistol = 0xBFD21232,
	WeaponSpecialCarbine = 0xC0A3098D,
	WeaponHeavyPistol = 0xD205520E,
	WeaponBullpupRifle = 0x7F229F94,
	WeaponHomingLauncher = 0x63AB0442,
	WeaponProximityMine = 0xAB564B93,
	WeaponSnowball = 0x787F0BB,
	WeaponVintagePistol = 0x83839C4,
	WeaponDagger = 0x92A27487,
	WeaponFirework = 0x7F7497E5,
	WeaponMusket = 0xA89CB99E,
	WeaponMarksmanRifle = 0xC734385A,
	WeaponHeavyShotgun = 0x3AABBBAA,
	WeaponGusenberg = 0x61012683,
	WeaponHatchet = 0xF9DCBF2D,
	WeaponRailgun = 0x6D544C99,
	WeaponUnarmed = 0xA2719263
};

enum eWeaponGroup : DWORD
{
	WeaponGroupUnarmed = 0xA00FC1E4,
	WeaponGroupMelee = 0xD49321D4,
	WeaponGroupPistol = 0x18D5FA97,
	WeaponGroupSMG = 0xC6E9A5C5,
	WeaponGroupAssaultRifle = 0xC7D15052,
	WeaponGroupMG = 0x451B04BC,
	WeaponGroupShotgun = 0x33431399,
	WeaponGroupSniper = 0xB7BBD827,
	WeaponGroupHeavy = 0xA27A4F9F,
	WeaponGroupThrown = 0x5C4C5883,
	WeaponGroupPetrolCan = 0x5F1BE07C
};

enum eWeaponTint
{
	WeaponTintNormal = 0,
	WeaponTintGreen = 1,
	WeaponTintGold = 2,
	WeaponTintPink = 3,
	WeaponTintArmy = 4,
	WeaponTintLSPD = 5,
	WeaponTintOrange = 6,
	WeaponTintPlatinum = 7
};

enum ePickupType : DWORD
{
	PickupTypeCustomScript = 0x2C014CA6,
	PickupTypeVehicleCustomScript = 0xA5B8CAA9,
	PickupTypeParachute = 0x6773257D,
	PickupTypePortablePackage = 0x80AB931C,
	PickupTypePortableCrateUnfixed = 0x6E717A95,

	PickupTypeHealth = 0x8F707C18,
	PickupTypeHealthSnack = 0x1CD2CF66,
	PickupTypeArmour = 0x4BFB42D1,

	PickupTypeMoneyCase = 0xCE6FDD6B,
	PickupTypeMoneySecurityCase = 0xDE78F17E,
	PickupTypeMoneyVariable = 0xFE18F3AF,
	PickupTypeMoneyMedBag = 0x14568F28,
	PickupTypeMoneyPurse = 0x1E9A99F8,
	PickupTypeMoneyDepBag = 0x20893292,
	PickupTypeMoneyWallet = 0x5DE0AD3E,
	PickupTypeMoneyPaperBag = 0x711D02A4,

	PickupTypeWeaponPistol = 0xF9AFB48F,
	PickupTypeWeaponCombatPistol = 0x8967B4F3,
	PickupTypeWeaponAPPistol = 0x3B662889,
	PickupTypeWeaponSNSPistol = 0xC5B72713,
	PickupTypeWeaponHeavyPistol = 0x9CF13918,
	PickupTypeWeaponMicroSMG = 0x1D9588D3,
	PickupTypeWeaponSMG = 0x3A4C2AD2,
	PickupTypeWeaponMG = 0x85CAA9B1,
	PickupTypeWeaponCombatMG = 0xB2930A14,
	PickupTypeWeaponAssaultRifle = 0xF33C83B0,
	PickupTypeWeaponCarbineRifle = 0xDF711959,
	PickupTypeWeaponAdvancedRifle = 0xB2B5325E,
	PickupTypeWeaponSpecialCarbine = 0x968339D,
	PickupTypeWeaponBullpupRifle = 0x815D66E8,
	PickupTypeWeaponPumpShotgun = 0xA9355DCD,
	PickupTypeWeaponSawnoffShotgun = 0x96B412A3,
	PickupTypeWeaponAssaultShotgun = 0x9299C95B,
	PickupTypeWeaponSniperRifle = 0xFE2A352C,
	PickupTypeWeaponHeavySniper = 0x693583AD,
	PickupTypeWeaponGrenadeLauncher = 0x2E764125,
	PickupTypeWeaponRPG = 0x4D36C349,
	PickupTypeWeaponMinigun = 0x2F36B434,
	PickupTypeWeaponGrenade = 0x5E0683A1,
	PickupTypeWeaponStickyBomb = 0x7C119D58,
	PickupTypeWeaponSmokeGrenade = 0x1CD604C7,
	PickupTypeWeaponMolotov = 0x2DD30479,
	PickupTypeWeaponPetrolCan = 0xC69DE3FF,
	PickupTypeWeaponKnife = 0x278D8734,
	PickupTypeWeaponNightstick = 0x5EA16D74,
	PickupTypeWeaponBat = 0x81EE601E,
	PickupTypeWeaponCrowbar = 0x872DC888,
	PickupTypeWeaponGolfclub = 0x88EAACA7,
	PickupTypeWeaponBottle = 0xFA51ABF5,

	PickupTypeVehicleWeaponPistol = 0xA54AE7B7,
	PickupTypeVehicleWeaponCombatPistol = 0xD0AACEF7,
	PickupTypeVehicleWeaponAPPistol = 0xCC8B3905,
	PickupTypeVehicleWeaponMicroSMG = 0xB86AEE5B,
	PickupTypeVehicleWeaponSawnoffShotgun = 0x2E071B5A,
	PickupTypeVehicleWeaponGrenade = 0xA717F898,
	PickupTypeVehicleWeaponSmokeGrenade = 0x65A7D8E9,
	PickupTypeVehicleWeaponStickyBomb = 0x2C804FE3,
	PickupTypeVehicleWeaponMolotov = 0x84D676D4,
	PickupTypeVehicleHealth = 0x98D79EF,

	PickupTypeAmmoPistol = 0x20796A82,
	PickupTypeAmmoSMG = 0x116FC4E6,
	PickupTypeAmmoMG = 0xDE58E0B3,
	PickupTypeAmmoRifle = 0xE4BD2FC6,
	PickupTypeAmmoShotgun = 0x77F3F2DD,
	PickupTypeAmmoSniper = 0xC02CF125,
	PickupTypeAmmoGrenadeLauncher = 0x881AB0A8,
	PickupTypeAmmoRPG = 0x84837FD7,
	PickupTypeAmmoMinigun = 0xF25A01B9,
	PickupTypeAmmoMissileMP = 0xF99E15D0,
	PickupTypeAmmoBulletMP = 0x550447A9,
	PickupTypeAmmoGrenadeLauncherMP = 0xA421A532
};

enum eHudComponent
{
	HudComponentMain = 0,
	HudComponentWantedStars,
	HudComponentWeaponIcon,
	HudComponentCash,
	HudComponentMpCash,
	HudComponentMpMessage,
	HudComponentVehicleName,
	HudComponentAreaName,
	HudComponentUnused,
	HudComponentStreetName,
	HudComponentHelpText,
	HudComponentFloatingHelpText1,
	HudComponentFloatingHelpText2,
	HudComponentCashChange,
	HudComponentReticle,
	HudComponentSubtitleText,
	HudComponentRadioStationsWheel,
	HudComponentSaving,
	HudComponentGameStreamUnused,
	HudComponentWeaponWheel,
	HudComponentWeaponWheelStats,
	HudComponentDrugsPurse01,
	HudComponentDrugsPurse02,
	HudComponentDrugsPurse03,
	HudComponentDrugsPurse04,
	HudComponentMpTagCashFromBank,
	HudComponentMpTagPackages,
	HudComponentMpTagCuffKeys,
	HudComponentMpTagDownloadData,
	HudComponentMpTagIfPedFollowing,
	HudComponentMpTagKeyCard,
	HudComponentMpTagRandomObject,
	HudComponentMpTagRemoteControl,
	HudComponentMpTagCashFromSafe,
	HudComponentMpTagWeaponsPackage,
	HudComponentMpTagKeys,
	HudComponentMpVehicle,
	HudComponentMpVehicleHeli,
	HudComponentMpVehiclePlane,
	HudComponentPlayerSwitchAlert,
	HudComponentMpRankBar,
	HudComponentDirectorMode,
	HudComponentReplayController,
	HudComponentReplayMouse,
	HudComponentReplayHeader,
	HudComponentReplayOptions,
	HudComponentReplayHelpText,
	HudComponentReplayMiscText,
	HudComponentReplayTopLine,
	HudComponentReplayBottomLine,
	HudComponentReplayLeftBar,
	HudComponentReplayTimer
};

enum eGameState {
	GameStatePlaying,
	GameStateIntro,
	GameStateLicenseShit = 3,
	GameStateMainMenu = 5,
	GameStateLoadingSP_MP = 6
};

struct teleportation_place {
	char* place_name;
	float x, y, z;
};

teleportation_place Places[] = {
	{ "Michael's House",-852.4f,160.0f,65.6f },
	{ "Franklin's House",7.9f,548.1f,175.5f },
	{ "Trevor's Trailer",1985.7f,3812.2f,32.2f },
	{ "Airport Entrance",-1034.6f,-2733.6f,13.8f },
	{ "Airport Field",-1336.0f,-3044.0f,13.9f },
	{ "Elysian Island",338.2f,-2715.9f,38.5f },
	{ "Jetsam",760.4f,-2943.2f,5.8f },
	{ "Stripclub",127.4f,-1307.7f,29.2f },
	{ "Elburro Heights",1384.0f,-2057.1f,52.0f },
	{ "Ferris Wheel",-1670.7f,-1125.0f,13.0f },
	{ "Chumash",-3192.6f,1100.0f,20.2f },
	{ "Windfarm",2354.0f,1830.3f,101.1f },
	{ "Military Base",-2047.4f,3132.1f,32.8f },
	{ "McKenzie Airfield",2121.7f,4796.3f,41.1f },
	{ "Desert Airfield",1747.0f,3273.7f,41.1f },
	{ "Chilliad",425.4f,5614.3f,766.5f },
	{ "Waypoint", 666.6f, 666.6f, 666.6f } };

LPCSTR vehiculeModels[63][10] = {
	{ "DINGHY", "DINGHY2", "DINGHY3", "DINGHY4", "JETMAX", "MARQUIS", "PREDATOR", "SEASHARK", "SEASHARK2", "SEASHARK3" },//boats
	{ "SPEEDER", "SPEEDER2", "SQUALO", "SUBMERSIBLE", "SUBMERSIBLE2","SUNTRAP", "TORO", "TORO2", "TROPIC", "TROPIC2" },//boats
	{ "TUG", "", "", "", "", "", "", "", "", "" },

	{ "BENSON", "BIFF", "HAULER", "MULE", "MULE2","MULE3", "PACKER", "PHANTOM", "PHANTOM2", "POUNDER" },//Commercial
	{ "STOCKADE","STOCKADE3", "", "", "", "", "", "", "", "" },//Commercial

	{ "BLISTA", "BRIOSO", "DILETTANTE", "DILETTANTE2", "ISSI2","PANTO", "PRAIRIE", "RHAPSODY", "", "" }, //Compacts

	{ "COGCABRIO", "EXEMPLAR", "F620", "FELON", "FELON2","JACKAL", "ORACLE", "ORACLE2", "SENTINEL", "SENTINEL2" }, //Coupes
	{ "WINDSOR", "WINDSOR2", "ZION", "ZION2", "", "", "", "", "", "" },//Coupes

	{ "BMX", "CRUISER", "FIXTER", "SCORCHER", "TRIBIKE","TRIBIKE2", "TRIBIKE3", "", "", "" }, //Cycles

	{ "AMBULANCE", "FBI", "FBI2", "FIRETRUK", "LGUARD","PBUS", "PRANGER", "POLICE", "POLICE2", "POLICE3" },//Emergency
	{ "POLICE4", "POLICEB", "POLICEOLD1", "POLICEOLD2", "POLICET","SHERIFF", "SHERIFF2", "RIOT", "", "" },// Emergency

	{ "ANNIHILATOR", "BLIMP", "BLIMP2", "BUZZARD", "BUZZARD2","CARGOBOB", "CARGOBOB2", "CARGOBOB3", "CARGOBOB4", "FROGGER" },//Helicopters
	{ "FROGGER2", "MAVERICK", "POLMAV", "SAVAGE", "SKYLIFT","SUPERVOLITO", "SUPERVOLITO2", "SWIFT", "SWIFT2", "VALKYRIE" },// Helicopters
	{ "VALKYRIE2", "VOLATUS", "", "", "", "", "", "", "", "" },// Helicopters

	{ "BULLDOZER", "CUTTER", "DUMP", "FLATBED", "GUARDIAN","HANDLER", "MIXER", "MIXER2", "RUBBLE", "TIPTRUCK" },//Industrial
	{ "TIPTRUCK2", "", "", "", "", "", "", "", "", "" },//Industrial

	{ "BARRACKS", "BARRACKS2", "BARRACKS3", "CRUSADER", "RHINO", "", "", "", "", "" },//Military

	{ "AKUMA", "AVARUS", "BAGGER", "BATI", "BATI2","BF400", "CARBONRS", "CHIMERA", "CLIFFHANGER", "DAEMON" },//Motorcycles
	{ "DAEMON2", "DEFILER", "DIABLOUS", "DIABLOUS2", "DOUBLE", "ENDURO", "ESSKEY","FAGGIO", "FAGGIO2", "FAGGIO3" },//Motorcycles
	{ "FCR", "FCR2", "GARGOYLE", "HAKUCHOU", "HAKUCHOU2", "HEXER", "INNOVATION", "LECTRO", "MANCHEZ", "NEMESIS" },//Motorcycles
	{ "NIGHTBLADE", "PCJ", "RATBIKE", "RUFFIAN","SANCHEZ", "SANCHEZ2", "SANCTUS", "SHOTARO", "SOVEREIGN","THRUST" },//Motorcycles
	{ "VADER", "VINDICATOR", "VORTEX", "WOLFSBANE","ZOMBIEA", "ZOMBIEB", "", "", "", "" },//Motorcycles

	{ "BLADE", "BUCCANEER", "BUCCANEER2", "CHINO", "CHINO2","COQUETTE3", "DOMINATOR", "DOMINATOR2", "DUKES", "DUKES2" },//Muscle
	{ "GAUNTLET", "GAUNTLET2", "FACTION", "FACTION2", "FACTION3","HOTKNIFE", "LURCHER", "MOONBEAM", "MOONBEAM2", "NIGHTSHADE" },//Muscle
	{ "PHOENIX", "PICADOR", "RATLOADER", "RATLOADER2", "RUINER", "RUINER2", "RUINER3","SABREGT", "SABREGT2", "SLAMVAN" },//Muscle
	{ "SLAMVAN2", "SLAMVAN3","STALION", "STALION2", "TAMPA", "VIGERO", "VIRGO","VIRGO2", "VIRGO3", "VOODOO" },// Muscle
	{ "VOODOO2", "", "", "", "", "", "", "", "", "" },//Muscle

	{ "BFINJECTION", "BIFTA", "BLAZER", "BLAZER2", "BLAZER3","BLAZER4", "BLAZER5", "BODHI2", "BRAWLER", "DLOADER" },//OffRoad
	{ "DUBSTA3","DUNE", "DUNE2", "DUNE4", "DUNE5", "INSURGENT", "INSURGENT2", "KALAHARI","MARSHALL", "MESA3" },//OffRoad
	{ "MONSTER", "RANCHERXL", "RANCHERXL2","REBEL", "REBEL2", "SANDKING", "SANDKING2", "TECHNICAL", "TECHNICAL2","TROPHYTRUCK" },//OffRoad
	{ "TROPHYTRUCK2", "", "", "", "", "", "", "", "", "" },//OffRoad

	{ "BESRA", "CARGOPLANE", "CUBAN800", "DODO", "DUSTER","HYDRA", "JET", "LAZER", "LUXOR", "LUXOR2" },//Planes
	{ "MAMMATUS", "MILJET", "NIMBUS", "SHAMAL", "STUNT","TITAN", "VELUM", "VELUM2", "VESTRA", "" },//Planes

	{ "ASEA", "ASEA2", "ASTEROPE", "COG55", "COG552","COGNOSCENTI", "COGNOSCENTI2", "EMPEROR", "EMPEROR2", "EMPEROR3" },//Sedans
	{ "FUGITIVE", "GLENDALE", "INGOT", "INTRUDER", "LIMO2","PREMIER", "PRIMO", "PRIMO2", "REGINA", "ROMERO" },// Sedans
	{ "SCHAFTER2", "SCHAFTER5", "SCHAFTER6", "STANIER", "STRATUM","STRETCH", "SUPERD", "SURGE", "TAILGATER", "WARRENER" },//Sedans
	{ "WASHINGTON", "", "", "", "", "", "", "", "", "" },//Sedans

	{ "AIRBUS", "BRICKADE", "BUS", "COACH", "RALLYTRUCK","RENTALBUS", "TAXI", "TOURBUS", "TRASH", "TRASH2" },//Service
	{ "WASTELANDER", "", "", "", "", "", "", "", "", "" },//Service

	{ "ALPHA", "BANSHEE", "BESTIAGTS", "BLISTA2", "BLISTA3","BUFFALO", "BUFFALO2", "BUFFALO3", "CARBONIZZARE", "COMET2" },//Sports
	{ "COMET3","COQUETTE", "ELEGY", "ELEGY2", "FELTZER2", "FUROREGT", "FUSILADE","FUTO", "JESTER", "JESTER2" },//Sports
	{ "KHAMELION", "KURUMA","KURUMA2", "LYNX", "MASSACRO", "MASSACRO2", "NINEF","NINEF2", "OMNIS", "PENUMBRA" },//Sports
	{ "RAPIDGT", "RAPIDGT2","RAPTOR", "SCHAFTER3", "SCHAFTER4", "SCHWARTZER", "SEVEN70", "SPECTER", "SPECTER2","SULTAN" },//Sports
	{ "SURANO", "TAMPA2", "TROPOS", "VERLIERER2", "", "", "", "", "", "" },

	{ "BTYPE", "BTYPE2", "BTYPE3", "CASCO", "COQUETTE2","FELTZER3", "JB700", "MAMBA", "MANANA", "MONROE" },//SportsClassics
	{ "PEYOTE", "PIGALLE", "STINGER", "STINGERGT", "TORNADO","TORNADO2", "TORNADO3", "TORNADO4", "TORNADO5", "TORNADO6" },//SportsClassics
	{ "ZTYPE", "", "", "", "", "", "", "", "", "" },//SportsClassics

	{ "ADDER", "BANSHEE2", "BULLET", "CHEETAH", "ENTITYXF","FMJ", "SHEAVA", "INFERNUS", "ITALIGTB", "ITALIGTB2" },//Super
	{ "NERO", "NERO2","OSIRIS", "LE7B", "PENETRATOR", "PFISTER811", "PROTOTIPO", "REAPER", "SULTANRS", "T20" },//Super
	{ "TEMPESTA", "TURISMOR", "TYRUS", "VACCA", "VOLTIC", "VOLTIC2", "ZENTORNO", "", "", "" },//Super

	{ "BALLER", "BALLER2", "BALLER3", "BALLER4", "BALLER5","BALLER6", "BJXL", "CAVALCADE", "CAVALCADE2", "CONTENDER" },//SUVs
	{ "DUBSTA", "DUBSTA2", "FQ2", "GRANGER", "GRESLEY","HABANERO", "HUNTLEY", "LANDSTALKER", "MESA", "MESA2" },//SUVs
	{ "PATRIOT", "RADI", "ROCOTO", "SEMINOLE", "SERRANO","XLS", "XLS2", "", "", "" },//SUVs

	{ "ARMYTANKER", "ARMYTRAILER", "ARMYTRAILER2", "BALETRAILER", "BOATTRAILER","DOCKTRAILER", "FREIGHTTRAILER", "GRAINTRAILER", "PROPTRAILER", "RAKETRAILER" },//Trailer
	{ "TANKER", "TANKER2", "TR2", "TR3", "TR4","TRAILERLOGS", "TRAILERS", "TRAILERS2", "TRAILERS3", "TRAILERSMALL" },//Trailer
	{ "TRFLAT", "TVTRAILER", "", "", "", "", "", "", "", "" },//Trailer

	{ "CABLECAR", "FREIGHT", "FREIGHTCAR", "FREIGHTCONT1", "FREIGHTCONT2","FREIGHTGRAIN", "METROTRAIN", "TANKERCAR", "", "" },//Trains

	{ "AIRTUG", "CADDY", "CADDY2", "DOCKTUG", "FORKLIFT","MOWER", "RIPLEY", "SADLER", "SADLER2", "SCRAP" },//Utility
	{ "TOWTRUCK", "TOWTRUCK2", "TRACTOR", "TRACTOR2", "TRACTOR3","UTILLITRUCK", "UTILLITRUCK2", "UTILLITRUCK3", "", "" },//Utility

	{ "BISON", "BISON2", "BISON3", "BOBCATXL", "BOXVILLE","BOXVILLE2", "BOXVILLE3", "BOXVILLE4", "BOXVILLE5", "BURRITO" },//Vans
	{ "BURRITO2","BURRITO3", "BURRITO4", "BURRITO5", "CAMPER", "GBURRITO","GBURRITO2", "JOURNEY", "MINIVAN", "MINIVAN2" },//Vans 
	{ "PARADISE","PONY", "PONY2", "RUMPO", "RUMPO2", "RUMPO3","SPEEDO", "SPEEDO2", "SURFER", "SURFER2" },
	{ "TACO","YOUGA", "YOUGA2", "", "", "", "", "", "", "" },//Vans

};

char* veh_cat(int index)
{
	switch (index)
	{
	case 1: case 2: case 3: return "Boats";
	case 4: case 5: return "Commercial";
	case 6: return "Compacts";
	case 7: case 8: return "Coupes";
	case 9: return "Cycles";
	case 10: case 11: return "Emergency";
	case 12: case 13: case 14: return "Helicopters";
	case 15: case 16: return "Industrial";
	case 17: return "Military";
	case 18: case 19: case 20: case 21: case 22: return "Motorcycles";
	case 23: case 24: case 25: case 26: case 27: return "Muscle";
	case 28: case 29: case 30: case 31: return "OffRoad";
	case 32: case 33: return "Planes";
	case 34: case 35: case 36: case 37: return "Sedans";
	case 38: case 39: return "Service";
	case 40: case 41: case  42: case 43: case 44: return "Sports";
	case 45: case 46: case  47:	return "SportsClassics";
	case 48: case 49: case 50: return "Super";
	case 51: case 52: case 53: return "Suv";
	case 54: case 55: case 56: return "Trailer";
	case 57: return "Trains";
	case 58: case 59: return "Utility";
	case 60: case 61: case 62: case 63:	return "Vans";
	default: return "Vehicules";
	}
}

char* veh_cat_array[] = { "Boats", "Commercial", "Compacts", "Coupes", "Cycles", "Emergency", "Helicopters", "Industrial", "Military", "Motorcycles", "Muscle", "OffRoad", "Planes", "Sedans", "Service", "Sports", "SportsClassics", "Super", "Suv", "Trailer", "Trains", "Utility", "Vans", "Vehicules" };

std::string MoneyModel[] = { "prop_gold_bar", "prop_weed_pallet", "Prop_weed_01", "prop_money_bag_01" };
LPCSTR MoneyModelMenu[] = { "Gold bar", "Weed pallet", "Weed plantation", "Money bag" };

LPCSTR platesTypes[] = { "Blue on white 1", "Yellow on black", "Yellow on blue", "Blue on white 2", "Blue on white 3", "North Yankton" };

LPCSTR pedModels[70][10] = {
	{ "player_zero", "player_one", "player_two", "a_c_boar", "a_c_chimp", "a_c_cow", "a_c_coyote", "a_c_deer", "a_c_fish", "a_c_hen" },
	{ "a_c_cat_01", "a_c_chickenhawk", "a_c_cormorant", "a_c_crow", "a_c_dolphin", "a_c_humpback", "a_c_killerwhale", "a_c_pigeon", "a_c_seagull", "a_c_sharkhammer" },
	{ "a_c_pig", "a_c_rat", "a_c_rhesus", "a_c_chop", "a_c_husky", "a_c_mtlion", "a_c_retriever", "a_c_sharktiger", "a_c_shepherd", "s_m_m_movalien_01" },
	{ "a_f_m_beach_01", "a_f_m_bevhills_01", "a_f_m_bevhills_02", "a_f_m_bodybuild_01", "a_f_m_business_02", "a_f_m_downtown_01", "a_f_m_eastsa_01", "a_f_m_eastsa_02", "a_f_m_fatbla_01", "a_f_m_fatcult_01" },
	{ "a_f_m_fatwhite_01", "a_f_m_ktown_01", "a_f_m_ktown_02", "a_f_m_prolhost_01", "a_f_m_salton_01", "a_f_m_skidrow_01", "a_f_m_soucentmc_01", "a_f_m_soucent_01", "a_f_m_soucent_02", "a_f_m_tourist_01" },
	{ "a_f_m_trampbeac_01", "a_f_m_tramp_01", "a_f_o_genstreet_01", "a_f_o_indian_01", "a_f_o_ktown_01", "a_f_o_salton_01", "a_f_o_soucent_01", "a_f_o_soucent_02", "a_f_y_beach_01", "a_f_y_bevhills_01" },
	{ "a_f_y_bevhills_02", "a_f_y_bevhills_03", "a_f_y_bevhills_04", "a_f_y_business_01", "a_f_y_business_02", "a_f_y_business_03", "a_f_y_business_04", "a_f_y_eastsa_01", "a_f_y_eastsa_02", "a_f_y_eastsa_03" },
	{ "a_f_y_epsilon_01", "a_f_y_fitness_01", "a_f_y_fitness_02", "a_f_y_genhot_01", "a_f_y_golfer_01", "a_f_y_hiker_01", "a_f_y_hippie_01", "a_f_y_hipster_01", "a_f_y_hipster_02", "a_f_y_hipster_03" },
	{ "a_f_y_hipster_04", "a_f_y_indian_01", "a_f_y_juggalo_01", "a_f_y_runner_01", "a_f_y_rurmeth_01", "a_f_y_scdressy_01", "a_f_y_skater_01", "a_f_y_soucent_01", "a_f_y_soucent_02", "a_f_y_soucent_03" },
	{ "a_f_y_tennis_01", "a_f_y_topless_01", "a_f_y_tourist_01", "a_f_y_tourist_02", "a_f_y_vinewood_01", "a_f_y_vinewood_02", "a_f_y_vinewood_03", "a_f_y_vinewood_04", "a_f_y_yoga_01", "a_m_m_acult_01" },
	{ "a_m_m_afriamer_01", "a_m_m_beach_01", "a_m_m_beach_02", "a_m_m_bevhills_01", "a_m_m_bevhills_02", "a_m_m_business_01", "a_m_m_eastsa_01", "a_m_m_eastsa_02", "a_m_m_farmer_01", "a_m_m_fatlatin_01" },
	{ "a_m_m_genfat_01", "a_m_m_genfat_02", "a_m_m_golfer_01", "a_m_m_hasjew_01", "a_m_m_hillbilly_01", "a_m_m_hillbilly_02", "a_m_m_indian_01", "a_m_m_ktown_01", "a_m_m_malibu_01", "a_m_m_mexcntry_01" },
	{ "a_m_m_mexlabor_01", "a_m_m_og_boss_01", "a_m_m_paparazzi_01", "a_m_m_polynesian_01", "a_m_m_prolhost_01", "a_m_m_rurmeth_01", "a_m_m_salton_01", "a_m_m_salton_02", "a_m_m_salton_03", "a_m_m_salton_04" },
	{ "a_m_m_skater_01", "a_m_m_skidrow_01", "a_m_m_socenlat_01", "a_m_m_soucent_01", "a_m_m_soucent_02", "a_m_m_soucent_03", "a_m_m_soucent_04", "a_m_m_stlat_02", "a_m_m_tennis_01", "a_m_m_tourist_01" },
	{ "a_m_m_trampbeac_01", "a_m_m_tramp_01", "a_m_m_tranvest_01", "a_m_m_tranvest_02", "a_m_o_acult_01", "a_m_o_acult_02", "a_m_o_beach_01", "a_m_o_genstreet_01", "a_m_o_ktown_01", "a_m_o_salton_01" },
	{ "a_m_o_soucent_01", "a_m_o_soucent_02", "a_m_o_soucent_03", "a_m_o_tramp_01", "a_m_y_acult_01", "a_m_y_acult_02", "a_m_y_beachvesp_01", "a_m_y_beachvesp_02", "a_m_y_beach_01", "a_m_y_beach_02" },
	{ "a_m_y_beach_03", "a_m_y_bevhills_01", "a_m_y_bevhills_02", "a_m_y_breakdance_01", "a_m_y_busicas_01", "a_m_y_business_01", "a_m_y_business_02", "a_m_y_business_03", "a_m_y_cyclist_01", "a_m_y_dhill_01" },
	{ "a_m_y_downtown_01", "a_m_y_eastsa_01", "a_m_y_eastsa_02", "a_m_y_epsilon_01", "a_m_y_epsilon_02", "a_m_y_gay_01", "a_m_y_gay_02", "a_m_y_genstreet_01", "a_m_y_genstreet_02", "a_m_y_golfer_01" },
	{ "a_m_y_hasjew_01", "a_m_y_hiker_01", "a_m_y_hippy_01", "a_m_y_hipster_01", "a_m_y_hipster_02", "a_m_y_hipster_03", "a_m_y_indian_01", "a_m_y_jetski_01", "a_m_y_juggalo_01", "a_m_y_ktown_01" },
	{ "a_m_y_ktown_02", "a_m_y_latino_01", "a_m_y_methhead_01", "a_m_y_mexthug_01", "a_m_y_motox_01", "a_m_y_motox_02", "a_m_y_musclbeac_01", "a_m_y_musclbeac_02", "a_m_y_polynesian_01", "a_m_y_roadcyc_01" },
	{ "a_m_y_runner_01", "a_m_y_runner_02", "a_m_y_salton_01", "a_m_y_skater_01", "a_m_y_skater_02", "a_m_y_soucent_01", "a_m_y_soucent_02", "a_m_y_soucent_03", "a_m_y_soucent_04", "a_m_y_stbla_01" },
	{ "a_m_y_stbla_02", "a_m_y_stlat_01", "a_m_y_stwhi_01", "a_m_y_stwhi_02", "a_m_y_sunbathe_01", "a_m_y_surfer_01", "a_m_y_vindouche_01", "a_m_y_vinewood_01", "a_m_y_vinewood_02", "a_m_y_vinewood_03" },
	{ "a_m_y_vinewood_04", "a_m_y_yoga_01", "u_m_y_proldriver_01", "u_m_y_rsranger_01", "u_m_y_sbike", "u_m_y_staggrm_01", "u_m_y_tattoo_01", "csb_abigail", "csb_anita", "csb_anton" },
	{ "csb_ballasog", "csb_bride", "csb_burgerdrug", "csb_car3guy1", "csb_car3guy2", "csb_chef", "csb_chin_goon", "csb_cletus", "csb_cop", "csb_customer" },
	{ "csb_denise_friend", "csb_fos_rep", "csb_g", "csb_groom", "csb_grove_str_dlr", "csb_hao", "csb_hugh", "csb_imran", "csb_janitor", "csb_maude" },
	{ "csb_mweather", "csb_ortega", "csb_oscar", "csb_porndudes", "csb_porndudes_p", "csb_prologuedriver", "csb_prolsec", "csb_ramp_gang", "csb_ramp_hic", "csb_ramp_hipster" },
	{ "csb_ramp_marine", "csb_ramp_mex", "csb_reporter", "csb_roccopelosi", "csb_screen_writer", "csb_stripper_01", "csb_stripper_02", "csb_tonya", "csb_trafficwarden", "cs_amandatownley" },
	{ "cs_andreas", "cs_ashley", "cs_bankman", "cs_barry", "cs_barry_p", "cs_beverly", "cs_beverly_p", "cs_brad", "cs_bradcadaver", "cs_carbuyer" },
	{ "cs_casey", "cs_chengsr", "cs_chrisformage", "cs_clay", "cs_dale", "cs_davenorton", "cs_debra", "cs_denise", "cs_devin", "cs_dom" },
	{ "cs_dreyfuss", "cs_drfriedlander", "cs_fabien", "cs_fbisuit_01", "cs_floyd", "cs_guadalope", "cs_gurk", "cs_hunter", "cs_janet", "cs_jewelass" },
	{ "cs_jimmyboston", "cs_jimmydisanto", "cs_joeminuteman", "cs_johnnyklebitz", "cs_josef", "cs_josh", "cs_lamardavis", "cs_lazlow", "cs_lestercrest", "cs_lifeinvad_01" },
	{ "cs_magenta", "cs_manuel", "cs_marnie", "cs_martinmadrazo", "cs_maryann", "cs_michelle", "cs_milton", "cs_molly", "cs_movpremf_01", "cs_movpremmale" },
	{ "cs_mrk", "cs_mrsphillips", "cs_mrs_thornhill", "cs_natalia", "cs_nervousron", "cs_nigel", "cs_old_man1a", "cs_old_man2", "cs_omega", "cs_orleans" },
	{ "cs_paper", "cs_paper_p", "cs_patricia", "cs_priest", "cs_prolsec_02", "cs_russiandrunk", "cs_siemonyetarian", "cs_solomon", "cs_stevehains", "cs_stretch" },
	{ "cs_tanisha", "cs_taocheng", "cs_taostranslator", "cs_tenniscoach", "cs_terry", "cs_tom", "cs_tomepsilon", "cs_tracydisanto", "cs_wade", "cs_zimbor" },
	{ "g_f_y_ballas_01", "g_f_y_families_01", "g_f_y_lost_01", "g_f_y_vagos_01", "g_m_m_armboss_01", "g_m_m_armgoon_01", "g_m_m_armlieut_01", "g_m_m_chemwork_01", "g_m_m_chemwork_01_p", "g_m_m_chiboss_01" },
	{ "g_m_m_chiboss_01_p", "g_m_m_chicold_01", "g_m_m_chicold_01_p", "g_m_m_chigoon_01", "g_m_m_chigoon_01_p", "g_m_m_chigoon_02", "g_m_m_korboss_01", "g_m_m_mexboss_01", "g_m_m_mexboss_02", "g_m_y_armgoon_02" },
	{ "g_m_y_azteca_01", "g_m_y_ballaeast_01", "g_m_y_ballaorig_01", "g_m_y_ballasout_01", "g_m_y_famca_01", "g_m_y_famdnf_01", "g_m_y_famfor_01", "g_m_y_korean_01", "g_m_y_korean_02", "g_m_y_korlieut_01" },
	{ "g_m_y_lost_01", "g_m_y_lost_02", "g_m_y_lost_03", "g_m_y_mexgang_01", "g_m_y_mexgoon_01", "g_m_y_mexgoon_02", "g_m_y_mexgoon_03", "g_m_y_mexgoon_03_p", "g_m_y_pologoon_01", "g_m_y_pologoon_01_p" },
	{ "g_m_y_pologoon_02", "g_m_y_pologoon_02_p", "g_m_y_salvaboss_01", "g_m_y_salvagoon_01", "g_m_y_salvagoon_02", "g_m_y_salvagoon_03", "g_m_y_salvagoon_03_p", "g_m_y_strpunk_01", "g_m_y_strpunk_02", "hc_driver" },
	{ "hc_gunman", "hc_hacker", "ig_abigail", "ig_amandatownley", "ig_andreas", "ig_ashley", "ig_ballasog", "ig_bankman", "ig_barry", "ig_barry_p" },
	{ "ig_bestmen", "ig_beverly", "ig_beverly_p", "ig_brad", "ig_bride", "ig_car3guy1", "ig_car3guy2", "ig_casey", "ig_chef", "ig_chengsr" },
	{ "ig_chrisformage", "ig_clay", "ig_claypain", "ig_cletus", "ig_dale", "ig_davenorton", "ig_denise", "ig_devin", "ig_dom", "ig_dreyfuss" },
	{ "ig_drfriedlander", "ig_fabien", "ig_fbisuit_01", "ig_floyd", "ig_groom", "ig_hao", "ig_hunter", "ig_janet", "ig_jay_norris", "ig_jewelass" },
	{ "ig_jimmyboston", "ig_jimmydisanto", "ig_joeminuteman", "ig_johnnyklebitz", "ig_josef", "ig_josh", "ig_kerrymcintosh", "ig_lamardavis", "ig_lazlow", "ig_lestercrest" },
	{ "ig_lifeinvad_01", "ig_lifeinvad_02", "ig_magenta", "ig_manuel", "ig_marnie", "ig_maryann", "ig_maude", "ig_michelle", "ig_milton", "ig_molly" },
	{ "ig_mrk", "ig_mrsphillips", "ig_mrs_thornhill", "ig_natalia", "ig_nervousron", "ig_nigel", "ig_old_man1a", "ig_old_man2", "ig_omega", "ig_oneil" },
	{ "ig_orleans", "ig_ortega", "ig_paper", "ig_patricia", "ig_priest", "ig_prolsec_02", "ig_ramp_gang", "ig_ramp_hic", "ig_ramp_hipster", "ig_ramp_mex" },
	{ "ig_roccopelosi", "ig_russiandrunk", "ig_screen_writer", "ig_siemonyetarian", "ig_solomon", "ig_stevehains", "ig_stretch", "ig_talina", "ig_tanisha", "ig_taocheng" },
	{ "ig_taostranslator", "ig_taostranslator_p", "ig_tenniscoach", "ig_terry", "ig_tomepsilon", "ig_tonya", "ig_tracydisanto", "ig_trafficwarden", "ig_tylerdix", "ig_wade" },
	{ "ig_zimbor", "mp_f_deadhooker", "mp_f_freemode_01", "mp_f_misty_01", "mp_f_stripperlite", "mp_g_m_pros_01", "mp_headtargets", "mp_m_claude_01", "mp_m_exarmy_01", "mp_m_famdd_01" },
	{ "mp_m_fibsec_01", "mp_m_freemode_01", "mp_m_marston_01", "mp_m_niko_01", "mp_m_shopkeep_01", "mp_s_m_armoured_01", "", "", "", "" },
	{ "", "s_f_m_fembarber", "s_f_m_maid_01", "s_f_m_shop_high", "s_f_m_sweatshop_01", "s_f_y_airhostess_01", "s_f_y_bartender_01", "s_f_y_baywatch_01", "s_f_y_cop_01", "s_f_y_factory_01" },
	{ "s_f_y_hooker_01", "s_f_y_hooker_02", "s_f_y_hooker_03", "s_f_y_migrant_01", "s_f_y_movprem_01", "s_f_y_ranger_01", "s_f_y_scrubs_01", "s_f_y_sheriff_01", "s_f_y_shop_low", "s_f_y_shop_mid" },
	{ "s_f_y_stripperlite", "s_f_y_stripper_01", "s_f_y_stripper_02", "s_f_y_sweatshop_01", "s_m_m_ammucountry", "s_m_m_armoured_01", "s_m_m_armoured_02", "s_m_m_autoshop_01", "s_m_m_autoshop_02", "s_m_m_bouncer_01" },
	{ "s_m_m_chemsec_01", "s_m_m_ciasec_01", "s_m_m_cntrybar_01", "s_m_m_dockwork_01", "s_m_m_doctor_01", "s_m_m_fiboffice_01", "s_m_m_fiboffice_02", "s_m_m_gaffer_01", "s_m_m_gardener_01", "s_m_m_gentransport" },
	{ "s_m_m_hairdress_01", "s_m_m_highsec_01", "s_m_m_highsec_02", "s_m_m_janitor", "s_m_m_lathandy_01", "s_m_m_lifeinvad_01", "s_m_m_linecook", "s_m_m_lsmetro_01", "s_m_m_mariachi_01", "s_m_m_marine_01" },
	{ "s_m_m_marine_02", "s_m_m_migrant_01", "u_m_y_zombie_01", "s_m_m_movprem_01", "s_m_m_movspace_01", "s_m_m_paramedic_01", "s_m_m_pilot_01", "s_m_m_pilot_02", "s_m_m_postal_01", "s_m_m_postal_02" },
	{ "s_m_m_prisguard_01", "s_m_m_scientist_01", "s_m_m_security_01", "s_m_m_snowcop_01", "s_m_m_strperf_01", "s_m_m_strpreach_01", "s_m_m_strvend_01", "s_m_m_trucker_01", "s_m_m_ups_01", "s_m_m_ups_02" },
	{ "s_m_o_busker_01", "s_m_y_airworker", "s_m_y_ammucity_01", "s_m_y_armymech_01", "s_m_y_autopsy_01", "s_m_y_barman_01", "s_m_y_baywatch_01", "s_m_y_blackops_01", "s_m_y_blackops_02", "s_m_y_busboy_01" },
	{ "s_m_y_chef_01", "s_m_y_clown_01", "s_m_y_construct_01", "s_m_y_construct_02", "s_m_y_cop_01", "s_m_y_dealer_01", "s_m_y_devinsec_01", "s_m_y_dockwork_01", "s_m_y_doorman_01", "s_m_y_dwservice_01" },
	{ "s_m_y_dwservice_02", "s_m_y_factory_01", "s_m_y_fireman_01", "s_m_y_garbage", "s_m_y_grip_01", "s_m_y_hwaycop_01", "s_m_y_marine_01", "s_m_y_marine_02", "s_m_y_marine_03", "s_m_y_mime" },
	{ "s_m_y_pestcont_01", "s_m_y_pilot_01", "s_m_y_prismuscl_01", "s_m_y_prisoner_01", "s_m_y_ranger_01", "s_m_y_robber_01", "s_m_y_sheriff_01", "s_m_y_shop_mask", "s_m_y_strvend_01", "s_m_y_swat_01" },
	{ "s_m_y_uscg_01", "s_m_y_valet_01", "s_m_y_waiter_01", "s_m_y_winclean_01", "s_m_y_xmech_01", "s_m_y_xmech_02", "u_f_m_corpse_01", "u_f_m_miranda", "u_f_m_promourn_01", "u_f_o_moviestar" },
	{ "u_f_o_prolhost_01", "u_f_y_bikerchic", "u_f_y_comjane", "u_f_y_corpse_01", "u_f_y_corpse_02", "u_f_y_hotposh_01", "u_f_y_jewelass_01", "u_f_y_mistress", "u_f_y_poppymich", "u_f_y_princess" },
	{ "u_f_y_spyactress", "u_m_m_aldinapoli", "u_m_m_bankman", "u_m_m_bikehire_01", "u_m_m_fibarchitect", "u_m_m_filmdirector", "u_m_m_glenstank_01", "u_m_m_griff_01", "u_m_m_jesus_01", "u_m_m_jewelsec_01" },
	{ "u_m_m_jewelthief", "u_m_m_markfost", "u_m_m_partytarget", "u_m_m_prolsec_01", "u_m_m_promourn_01", "u_m_m_rivalpap", "u_m_m_spyactor", "u_m_m_willyfist", "u_m_o_finguru_01", "u_m_o_taphillbilly" },
	{ "u_m_o_tramp_01", "u_m_y_abner", "u_m_y_antonb", "u_m_y_babyd", "u_m_y_baygor", "u_m_y_burgerdrug_01", "u_m_y_chip", "u_m_y_cyclist_01", "u_m_y_fibmugger_01", "u_m_y_guido_01" },
	{ "u_m_y_gunvend_01", "u_m_y_hippie_01", "u_m_y_imporage", "u_m_y_justin", "u_m_y_mani", "u_m_y_militarybum", "u_m_y_paparazzi", "u_m_y_party_01", "u_m_y_pogo_01", "u_m_y_prisoner_01" },
	{ "ig_benny", "ig_g", "ig_vagspeak", "mp_m_g_vagfun_01", "mp_m_boatstaff_01", "mp_f_boatstaff_01", "", "", "", "" }
};

LPCSTR pedModelNames[70][10] = {
	{ "MICHAEL", "FRANKLIN", "TREVOR", "BOAR", "CHIMP", "COW", "COYOTE", "DEER", "FISH", "HEN" },
	{ "CAT", "HAWK", "CORMORANT", "CROW", "DOLPHIN", "HUMPBACK", "WHALE", "PIGEON", "SEAGULL", "SHARKHAMMER" },
	{ "PIG", "RAT", "RHESUS", "CHOP", "HUSKY", "MTLION", "RETRIEVER", "SHARKTIGER", "SHEPHERD", "ALIEN" },
	{ "BEACH", "BEVHILLS", "BEVHILLS", "BODYBUILD", "BUSINESS", "DOWNTOWN", "EASTSA", "EASTSA", "FATBLA", "FATCULT" },
	{ "FATWHITE", "KTOWN", "KTOWN", "PROLHOST", "SALTON", "SKIDROW", "SOUCENTMC", "SOUCENT", "SOUCENT", "TOURIST" },
	{ "TRAMPBEAC", "TRAMP", "GENSTREET", "INDIAN", "KTOWN", "SALTON", "SOUCENT", "SOUCENT", "BEACH", "BEVHILLS" },
	{ "BEVHILLS", "BEVHILLS", "BEVHILLS", "BUSINESS", "BUSINESS", "BUSINESS", "BUSINESS", "EASTSA", "EASTSA", "EASTSA" },
	{ "EPSILON", "FITNESS", "FITNESS", "GENHOT", "GOLFER", "HIKER", "HIPPIE", "HIPSTER", "HIPSTER", "HIPSTER" },
	{ "HIPSTER", "INDIAN", "JUGGALO", "RUNNER", "RURMETH", "SCDRESSY", "SKATER", "SOUCENT", "SOUCENT", "SOUCENT" },
	{ "TENNIS", "TOPLESS", "TOURIST", "TOURIST", "VINEWOOD", "VINEWOOD", "VINEWOOD", "VINEWOOD", "YOGA", "ACULT" },
	{ "AFRIAMER", "BEACH", "BEACH", "BEVHILLS", "BEVHILLS", "BUSINESS", "EASTSA", "EASTSA", "FARMER", "FATLATIN" },
	{ "GENFAT", "GENFAT", "GOLFER", "HASJEW", "HILLBILLY", "HILLBILLY", "INDIAN", "KTOWN", "MALIBU", "MEXCNTRY" },
	{ "MEXLABOR", "OG_BOSS", "PAPARAZZI", "POLYNESIAN", "PROLHOST", "RURMETH", "SALTON", "SALTON", "SALTON", "SALTON" },
	{ "SKATER", "SKIDROW", "SOCENLAT", "SOUCENT", "SOUCENT", "SOUCENT", "SOUCENT", "STLAT", "TENNIS", "TOURIST" },
	{ "TRAMPBEAC", "TRAMP", "TRANVEST", "TRANVEST", "ACULT", "ACULT", "BEACH", "GENSTREET", "KTOWN", "SALTON" },
	{ "SOUCENT", "SOUCENT", "SOUCENT", "TRAMP", "ACULT", "ACULT", "BEACHVESP", "BEACHVESP", "BEACH", "BEACH" },
	{ "BEACH", "BEVHILLS", "BEVHILLS", "BREAKDANCE", "BUSICAS", "BUSINESS", "BUSINESS", "BUSINESS", "CYCLIST", "DHILL" },
	{ "DOWNTOWN", "EASTSA", "EASTSA", "EPSILON", "EPSILON", "GAY", "GAY", "GENSTREET", "GENSTREET", "GOLFER" },
	{ "HASJEW", "HIKER", "HIPPY", "HIPSTER", "HIPSTER", "HIPSTER", "INDIAN", "JETSKI", "JUGGALO", "KTOWN" },
	{ "KTOWN", "LATINO", "METHHEAD", "MEXTHUG", "MOTOX", "MOTOX", "MUSCLBEAC", "MUSCLBEAC", "POLYNESIAN", "ROADCYC" },
	{ "RUNNER", "RUNNER", "SALTON", "SKATER", "SKATER", "SOUCENT", "SOUCENT", "SOUCENT", "SOUCENT", "STBLA" },
	{ "STBLA", "STLAT", "STWHI", "STWHI", "SUNBATHE", "SURFER", "VINDOUCHE", "VINEWOOD", "VINEWOOD", "VINEWOOD" },
	{ "VINEWOOD", "YOGA", "PROLDRIVER", "RSRANGER", "SBIKE", "STAGGRM", "TATTOO", "ABIGAIL", "ANITA", "ANTON" },
	{ "BALLASOG", "BRIDE", "BURGERDRUG", "CAR3GUY1", "CAR3GUY2", "CHEF", "CHIN_GOON", "CLETUS", "COP", "CUSTOMER" },
	{ "DENISE_FRIEND", "FOS_REP", "G", "GROOM", "DLR", "HAO", "HUGH", "IMRAN", "JANITOR", "MAUDE" },
	{ "MWEATHER", "ORTEGA", "OSCAR", "PORNDUDES", "PORNDUDES_P", "PROLOGUEDRIVER", "PROLSEC", "GANG", "HIC", "HIPSTER" },
	{ "MARINE", "MEX", "REPORTER", "ROCCOPELOSI", "SCREEN_WRITER", "STRIPPER", "STRIPPER", "TONYA", "TRAFFICWARDEN", "AMANDATOWNLEY" },
	{ "ANDREAS", "ASHLEY", "BANKMAN", "BARRY", "BARRY_P", "BEVERLY", "BEVERLY_P", "BRAD", "BRADCADAVER", "CARBUYER" },
	{ "CASEY", "CHENGSR", "CHRISFORMAGE", "CLAY", "DALE", "DAVENORTON", "DEBRA", "DENISE", "DEVIN", "DOM" },
	{ "DREYFUSS", "DRFRIEDLANDER", "FABIEN", "FBISUIT", "FLOYD", "GUADALOPE", "GURK", "HUNTER", "JANET", "JEWELASS" },
	{ "JIMMYBOSTON", "JIMMYDISANTO", "JOEMINUTEMAN", "JOHNNYKLEBITZ", "JOSEF", "JOSH", "LAMARDAVIS", "LAZLOW", "LESTERCREST", "LIFEINVAD" },
	{ "MAGENTA", "MANUEL", "MARNIE", "MARTINMADRAZO", "MARYANN", "MICHELLE", "MILTON", "MOLLY", "MOVPREMF", "MOVPREMMALE" },
	{ "MRK", "MRSPHILLIPS", "MRS_THORNHILL", "NATALIA", "NERVOUSRON", "NIGEL", "OLD_MAN1A", "OLD_MAN2", "OMEGA", "ORLEANS" },
	{ "PAPER", "PAPER_P", "PATRICIA", "PRIEST", "PROLSEC", "RUSSIANDRUNK", "SIEMONYETARIAN", "SOLOMON", "STEVEHAINS", "STRETCH" },
	{ "TANISHA", "TAOCHENG", "TAOSTRANSLATOR", "TENNISCOACH", "TERRY", "TOM", "TOMEPSILON", "TRACYDISANTO", "WADE", "ZIMBOR" },
	{ "BALLAS", "FAMILIES", "LOST", "VAGOS", "ARMBOSS", "ARMGOON", "ARMLIEUT", "CHEMWORK", "CHEMWORK_P", "CHIBOSS" },
	{ "CHIBOSS_P", "CHICOLD", "CHICOLD_P", "CHIGOON", "CHIGOON_P", "CHIGOON", "KORBOSS", "MEXBOSS", "MEXBOSS", "ARMGOON" },
	{ "AZTECA", "BALLAEAST", "BALLAORIG", "BALLASOUT", "FAMCA", "FAMDNF", "FAMFOR", "KOREAN", "KOREAN", "KORLIEUT" },
	{ "LOST", "LOST", "LOST", "MEXGANG", "MEXGOON", "MEXGOON", "MEXGOON", "MEXGOON_P", "POLOGOON", "POLOGOON_P" },
	{ "POLOGOON", "POLOGOON_P", "SALVABOSS", "SALVAGOON", "SALVAGOON", "SALVAGOON", "SALVAGOON_P", "STRPUNK", "STRPUNK", "HC_DRIVER" },
	{ "HC_GUNMAN", "HC_HACKER", "ABIGAIL", "AMANDATOWNLEY", "ANDREAS", "ASHLEY", "BALLASOG", "BANKMAN", "BARRY", "BARRY_P" },
	{ "BESTMEN", "BEVERLY", "BEVERLY_P", "BRAD", "BRIDE", "CAR3GUY1", "CAR3GUY2", "CASEY", "CHEF", "CHENGSR" },
	{ "CHRISFORMAGE", "CLAY", "CLAYPAIN", "CLETUS", "DALE", "DAVENORTON", "DENISE", "DEVIN", "DOM", "DREYFUSS" },
	{ "DRFRIEDLANDER", "FABIEN", "FBISUIT", "FLOYD", "GROOM", "HAO", "HUNTER", "JANET", "JAY_NORRIS", "JEWELASS" },
	{ "JIMMYBOSTON", "JIMMYDISANTO", "JOEMINUTEMAN", "JOHNNYKLEBITZ", "JOSEF", "JOSH", "KERRYMCINTOSH", "LAMARDAVIS", "LAZLOW", "LESTERCREST" },
	{ "LIFEINVAD", "LIFEINVAD", "MAGENTA", "MANUEL", "MARNIE", "MARYANN", "MAUDE", "MICHELLE", "MILTON", "MOLLY" },
	{ "MRK", "MRSPHILLIPS", "MRS_THORNHILL", "NATALIA", "NERVOUSRON", "NIGEL", "OLD_MAN1A", "OLD_MAN2", "OMEGA", "ONEIL" },
	{ "ORLEANS", "ORTEGA", "PAPER", "PATRICIA", "PRIEST", "PROLSEC", "GANG", "HIC", "HIPSTER", "MEX" },
	{ "ROCCOPELOSI", "RUSSIANDRUNK", "SCREEN_WRITER", "SIEMONYETARIAN", "SOLOMON", "STEVEHAINS", "STRETCH", "TALINA", "TANISHA", "TAOCHENG" },
	{ "TAOSTRANSLATOR", "TAOSTRANSLATOR_P", "TENNISCOACH", "TERRY", "TOMEPSILON", "TONYA", "TRACYDISANTO", "TRAFFICWARDEN", "TYLERDIX", "WADE" },
	{ "ZIMBOR", "DEADHOOKER", "FREEMODE", "MISTY", "STRIPPERLITE", "PROS", "MP_HEADTARGETS", "CLAUDE", "EXARMY", "FAMDD" },
	{ "FIBSEC", "FREEMODE", "MARSTON", "NIKO", "SHOPKEEP", "ARMOURED", "NONE", "NONE", "NONE", "NONE" },
	{ "NONE", "FEMBARBER", "MAID", "SHOP_HIGH", "SWEATSHOP", "AIRHOSTESS", "BARTENDER", "BAYWATCH", "COP", "FACTORY" },
	{ "HOOKER", "HOOKER", "HOOKER", "MIGRANT", "MOVPREM", "RANGER", "SCRUBS", "SHERIFF", "SHOP_LOW", "SHOP_MID" },
	{ "STRIPPERLITE", "STRIPPER", "STRIPPER", "SWEATSHOP", "AMMUCOUNTRY", "ARMOURED", "ARMOURED", "AUTOSHOP", "AUTOSHOP", "BOUNCER" },
	{ "CHEMSEC", "CIASEC", "CNTRYBAR", "DOCKWORK", "DOCTOR", "FIBOFFICE", "FIBOFFICE", "GAFFER", "GARDENER", "GENTRANSPORT" },
	{ "HAIRDRESS", "HIGHSEC", "HIGHSEC", "JANITOR", "LATHANDY", "LIFEINVAD", "LINECOOK", "LSMETRO", "MARIACHI", "MARINE" },
	{ "MARINE", "MIGRANT", "ZOMBIE", "MOVPREM", "MOVSPACE", "PARAMEDIC", "PILOT", "PILOT", "POSTAL", "POSTAL" },
	{ "PRISGUARD", "SCIENTIST", "SECURITY", "SNOWCOP", "STRPERF", "STRPREACH", "STRVEND", "TRUCKER", "UPS", "UPS" },
	{ "BUSKER", "AIRWORKER", "AMMUCITY", "ARMYMECH", "AUTOPSY", "BARMAN", "BAYWATCH", "BLACKOPS", "BLACKOPS", "BUSBOY" },
	{ "CHEF", "CLOWN", "CONSTRUCT", "CONSTRUCT", "COP", "DEALER", "DEVINSEC", "DOCKWORK", "DOORMAN", "DWSERVICE" },
	{ "DWSERVICE", "FACTORY", "FIREMAN", "GARBAGE", "GRIP", "HWAYCOP", "MARINE", "MARINE", "MARINE", "MIME" },
	{ "PESTCONT", "PILOT", "PRISMUSCL", "PRISONER", "RANGER", "ROBBER", "SHERIFF", "SHOP_MASK", "STRVEND", "SWAT" },
	{ "USCG", "VALET", "WAITER", "WINCLEAN", "XMECH", "XMECH", "CORPSE", "MIRANDA", "PROMOURN", "MOVIESTAR" },
	{ "PROLHOST", "BIKERCHIC", "COMJANE", "CORPSE", "CORPSE", "HOTPOSH", "JEWELASS", "MISTRESS", "POPPYMICH", "PRINCESS" },
	{ "SPYACTRESS", "ALDINAPOLI", "BANKMAN", "BIKEHIRE", "FIBARCHITECT", "FILMDIRECTOR", "GLENSTANK", "GRIFF", "JESUS", "JEWELSEC" },
	{ "JEWELTHIEF", "MARKFOST", "PARTYTARGET", "PROLSEC", "PROMOURN", "RIVALPAP", "SPYACTOR", "WILLYFIST", "FINGURU", "TAPHILLBILLY" },
	{ "TRAMP", "ABNER", "ANTONB", "BABYD", "BAYGOR", "BURGERDRUG", "CHIP", "CYCLIST", "FIBMUGGER", "GUIDO" },
	{ "GUNVEND", "HIPPIE", "IMPORAGE", "JUSTIN", "MANI", "MILITARYBUM", "PAPARAZZI", "PARTY", "POGO", "PRISONER" },
	{ "BENNY", "G", "VAGSPEAK", "VAGFUN", "BOATSTAFF", "FEMBOATSTAFF", "", "", "", "" }
};